/*L
   Copyright SAIC
   Copyright SAIC-Frederick

   Distributed under the OSI-approved BSD 3-Clause License.
   See http://ncip.github.com/cananolab/LICENSE.txt for details.
L*/

USE canano;

ALTER TABLE canano.common_lookup
 CHANGE common_lookup_pk_id common_lookup_pk_id BIGINT(20) AUTO_INCREMENT NOT NULL;
 
INSERT INTO common_lookup (name,attribute,value) VALUES ('asymmetrical flow field-flow fractionation with multi-angle laser light scattering','abbreviation','AFFF-MALLS');
INSERT INTO common_lookup (name,attribute,value) VALUES ('atomic force microscopy','abbreviation','AFM');
INSERT INTO common_lookup (name,attribute,value) VALUES ('confocal laser scanning microscopy','abbreviation','CLSM');
INSERT INTO common_lookup (name,attribute,value) VALUES ('dynamic light scattering','abbreviation','DLS');
INSERT INTO common_lookup (name,attribute,value) VALUES ('electron microprobe analysis','abbreviation','EMPA');
INSERT INTO common_lookup (name,attribute,value) VALUES ('energy dispersive spectroscopy','abbreviation','EDS');
INSERT INTO common_lookup (name,attribute,value) VALUES ('environmental transmission electron microscopy','abbreviation','ETEM');
INSERT INTO common_lookup (name,attribute,value) VALUES ('fast protein liquid chromatography','abbreviation','FPLC');
INSERT INTO common_lookup (name,attribute,value) VALUES ('focused ion beam - scanning electron microscopy','abbreviation','FIB-SEM');
INSERT INTO common_lookup (name,attribute,value) VALUES ('gel filtration chromatography','abbreviation','GFC');
INSERT INTO common_lookup (name,attribute,value) VALUES ('high performance liquid chromatography','abbreviation','HPLC');
INSERT INTO common_lookup (name,attribute,value) VALUES ('high resolution scanning electron microscopy','abbreviation','HR-SEM');
INSERT INTO common_lookup (name,attribute,value) VALUES ('high resolution transmission electron microscopy','abbreviation','HRTEM');
INSERT INTO common_lookup (name,attribute,value) VALUES ('matrix assisted laser desorption ionisation - time of flight','abbreviation','MALDI-TOF');
INSERT INTO common_lookup (name,attribute,value) VALUES ('multi-angle laser light scattering','abbreviation','MALLS');
INSERT INTO common_lookup (name,attribute,value) VALUES ('polymerase chain reaction','abbreviation','PCR');
INSERT INTO common_lookup (name,attribute,value) VALUES ('scanning auger spectrometry','abbreviation','SAM');
INSERT INTO common_lookup (name,attribute,value) VALUES ('scanning electron microscopy','abbreviation','SEM');
INSERT INTO common_lookup (name,attribute,value) VALUES ('scanning probe microscopy ','abbreviation','SPM');
INSERT INTO common_lookup (name,attribute,value) VALUES ('scanning tunneling  microscopy','abbreviation','STM');
INSERT INTO common_lookup (name,attribute,value) VALUES ('size exclusion chromatography with multi-angle laser light scattering','abbreviation','SEC-MALLS');
INSERT INTO common_lookup (name,attribute,value) VALUES ('transmission electron microscopy','abbreviation','TEM');
INSERT INTO common_lookup (name,attribute,value) VALUES ('X-ray photoelectron spectroscopy','abbreviation','XPS');
INSERT INTO common_lookup (name,attribute,value) VALUES ('blood contact','assayType','coagulation');
INSERT INTO common_lookup (name,attribute,value) VALUES ('blood contact','assayType','complement activation');
INSERT INTO common_lookup (name,attribute,value) VALUES ('blood contact','assayType','hemolysis');
INSERT INTO common_lookup (name,attribute,value) VALUES ('blood contact','assayType','plasma protein binding');
INSERT INTO common_lookup (name,attribute,value) VALUES ('blood contact','assayType','platelet aggregation');
INSERT INTO common_lookup (name,attribute,value) VALUES ('cytotoxicity','assayType','caspase 3 apoptosis');
INSERT INTO common_lookup (name,attribute,value) VALUES ('cytotoxicity','assayType','cell viability');
INSERT INTO common_lookup (name,attribute,value) VALUES ('cytotoxicity','assayType','gene expression');
INSERT INTO common_lookup (name,attribute,value) VALUES ('cytotoxicity','assayType','mitochondrial function');
INSERT INTO common_lookup (name,attribute,value) VALUES ('cytotoxicity','assayType','mitochondrial membrane potential');
INSERT INTO common_lookup (name,attribute,value) VALUES ('cytotoxicity','assayType','proliferation');
INSERT INTO common_lookup (name,attribute,value) VALUES ('immune cell function','assayType','CFU-GM');
INSERT INTO common_lookup (name,attribute,value) VALUES ('immune cell function','assayType','chemotaxis');
INSERT INTO common_lookup (name,attribute,value) VALUES ('immune cell function','assayType','cytokine induction');
INSERT INTO common_lookup (name,attribute,value) VALUES ('immune cell function','assayType','cytotoxic activity of nk cells');
INSERT INTO common_lookup (name,attribute,value) VALUES ('immune cell function','assayType','leukocyte proliferation');
INSERT INTO common_lookup (name,attribute,value) VALUES ('immune cell function','assayType','oxidative burst');
INSERT INTO common_lookup (name,attribute,value) VALUES ('immune cell function','assayType','phagocytosis');
INSERT INTO common_lookup (name,attribute,value) VALUES ('oxidative stress','assayType','gsh homeostasis');
INSERT INTO common_lookup (name,attribute,value) VALUES ('oxidative stress','assayType','lipid peroxidation');
INSERT INTO common_lookup (name,attribute,value) VALUES ('oxidative stress','assayType','ros generation');
INSERT INTO common_lookup (name,attribute,value) VALUES ('sterility','assayType','bacterial/yeast/mold');
INSERT INTO common_lookup (name,attribute,value) VALUES ('sterility','assayType','endotoxin');
INSERT INTO common_lookup (name,attribute,value) VALUES ('sterility','assayType','mycoplasma');
INSERT INTO common_lookup (name,attribute,value) VALUES ('targeting','assayType','cell binding/internalization');
INSERT INTO common_lookup (name,attribute,value) VALUES ('targeting','assayType','gene expression');
INSERT INTO common_lookup (name,attribute,value) VALUES ('attachment','bondType','covalent');
INSERT INTO common_lookup (name,attribute,value) VALUES ('attachment','bondType','electrostatic');
INSERT INTO common_lookup (name,attribute,value) VALUES ('attachment','bondType','hydrogen');
INSERT INTO common_lookup (name,attribute,value) VALUES ('attachment','bondType','ionic');
INSERT INTO common_lookup (name,attribute,value) VALUES ('attachment','bondType','van der Waals');
INSERT INTO common_lookup (name,attribute,value) VALUES ('publication','category','book chapter');
INSERT INTO common_lookup (name,attribute,value) VALUES ('publication','category','editorial');
INSERT INTO common_lookup (name,attribute,value) VALUES ('publication','category','peer review article');
INSERT INTO common_lookup (name,attribute,value) VALUES ('publication','category','proceeding');
INSERT INTO common_lookup (name,attribute,value) VALUES ('publication','category','report');
INSERT INTO common_lookup (name,attribute,value) VALUES ('publication','category','review');
INSERT INTO common_lookup (name,attribute,value) VALUES ('emulsion','composingElementType','bulk phase');
INSERT INTO common_lookup (name,attribute,value) VALUES ('emulsion','composingElementType','dispersed phase');
INSERT INTO common_lookup (name,attribute,value) VALUES ('emulsion','composingElementType','emulsifier');
INSERT INTO common_lookup (name,attribute,value) VALUES ('caspase 3 apoptosis','datumName','% of control');
INSERT INTO common_lookup (name,attribute,value) VALUES ('caspase 3 apoptosis','datumName','fluorescence');
INSERT INTO common_lookup (name,attribute,value) VALUES ('cell binding/internalization','datumName','cellular fluorescence');
INSERT INTO common_lookup (name,attribute,value) VALUES ('cell viability','datumName','LC50');
INSERT INTO common_lookup (name,attribute,value) VALUES ('CFU-GM','datumName','number of CFU-GM colonies');
INSERT INTO common_lookup (name,attribute,value) VALUES ('CFU-GM','datumName','total number of bone marrow cells');
INSERT INTO common_lookup (name,attribute,value) VALUES ('chemotaxis','datumName','% of control');
INSERT INTO common_lookup (name,attribute,value) VALUES ('coagulation','datumName','activated partial thromboplastin time (APTT)');
INSERT INTO common_lookup (name,attribute,value) VALUES ('coagulation','datumName','prothrombin time (PT)');
INSERT INTO common_lookup (name,attribute,value) VALUES ('coagulation','datumName','reptilase time');
INSERT INTO common_lookup (name,attribute,value) VALUES ('coagulation','datumName','thrombin time');
INSERT INTO common_lookup (name,attribute,value) VALUES ('complement activation','datumName','is complement activation induced?');
INSERT INTO common_lookup (name,attribute,value) VALUES ('cytokine induction','datumName','IL1 Beta');
INSERT INTO common_lookup (name,attribute,value) VALUES ('cytokine induction','datumName','IL10');
INSERT INTO common_lookup (name,attribute,value) VALUES ('cytokine induction','datumName','IL6');
INSERT INTO common_lookup (name,attribute,value) VALUES ('cytokine induction','datumName','IL8');
INSERT INTO common_lookup (name,attribute,value) VALUES ('cytokine induction','datumName','TNF Alpha');
INSERT INTO common_lookup (name,attribute,value) VALUES ('cytotoxic activity of nk cells','datumName','% of control');
INSERT INTO common_lookup (name,attribute,value) VALUES ('enzyme induction','datumName','% of control');
INSERT INTO common_lookup (name,attribute,value) VALUES ('gene expression','datumName','cellular fluorescence');
INSERT INTO common_lookup (name,attribute,value) VALUES ('gene expression','datumName','fluorescence ratio');
INSERT INTO common_lookup (name,attribute,value) VALUES ('gsh homeostasis','datumName','% of control');
INSERT INTO common_lookup (name,attribute,value) VALUES ('hemolysis','datumName','is hemolytic?');
INSERT INTO common_lookup (name,attribute,value) VALUES ('leukocyte proliferation','datumName','% of control');
INSERT INTO common_lookup (name,attribute,value) VALUES ('lipid peroxidation','datumName','% of control');
INSERT INTO common_lookup (name,attribute,value) VALUES ('mitochondrial function','datumName','luminescence');
INSERT INTO common_lookup (name,attribute,value) VALUES ('mitochondrial membrane potential','datumName','fluorescence ratio');
INSERT INTO common_lookup (name,attribute,value) VALUES ('mitochondrial membrane potential','datumName','ratio of red to green fluorescence');
INSERT INTO common_lookup (name,attribute,value) VALUES ('molecular weight','datumName','molecular weight');
INSERT INTO common_lookup (name,attribute,value) VALUES ('oxidative burst','datumName','% of control');
INSERT INTO common_lookup (name,attribute,value) VALUES ('phagocytosis','datumName','fold change vs. control');
INSERT INTO common_lookup (name,attribute,value) VALUES ('plasma protein binding','datumName','peptide bound');
INSERT INTO common_lookup (name,attribute,value) VALUES ('plasma protein binding','datumName','protein bound');
INSERT INTO common_lookup (name,attribute,value) VALUES ('platelet aggregation','datumName','% of aggregation vs. control');
INSERT INTO common_lookup (name,attribute,value) VALUES ('platelet aggregation','datumName','% of collagen induced aggregation vs. control');
INSERT INTO common_lookup (name,attribute,value) VALUES ('platelet aggregation','datumName','is above threshold?');
INSERT INTO common_lookup (name,attribute,value) VALUES ('proliferation','datumName','% of control');
INSERT INTO common_lookup (name,attribute,value) VALUES ('proliferation','datumName','ratio of cell line1 to cell line 2');
INSERT INTO common_lookup (name,attribute,value) VALUES ('purity','datumName','% purity for sample');
INSERT INTO common_lookup (name,attribute,value) VALUES ('relaxivity','datumName','R1');
INSERT INTO common_lookup (name,attribute,value) VALUES ('relaxivity','datumName','R2');
INSERT INTO common_lookup (name,attribute,value) VALUES ('relaxivity','datumName','T1');
INSERT INTO common_lookup (name,attribute,value) VALUES ('relaxivity','datumName','T2');
INSERT INTO common_lookup (name,attribute,value) VALUES ('ros generation','datumName','% of control');
INSERT INTO common_lookup (name,attribute,value) VALUES ('size','datumName','PDI');
INSERT INTO common_lookup (name,attribute,value) VALUES ('size','datumName','size');
INSERT INTO common_lookup (name,attribute,value) VALUES ('surface','datumName','charge');
INSERT INTO common_lookup (name,attribute,value) VALUES ('surface','datumName','surface area');
INSERT INTO common_lookup (name,attribute,value) VALUES ('surface','datumName','zeta potential');
INSERT INTO common_lookup (name,attribute,value) VALUES ('asymmetrical flow field-flow fractionation with multi-angle laser light scattering','instrument','control module');
INSERT INTO common_lookup (name,attribute,value) VALUES ('asymmetrical flow field-flow fractionation with multi-angle laser light scattering','instrument','photometer');
INSERT INTO common_lookup (name,attribute,value) VALUES ('asymmetrical flow field-flow fractionation with multi-angle laser light scattering','instrument','refractometer');
INSERT INTO common_lookup (name,attribute,value) VALUES ('asymmetrical flow field-flow fractionation with multi-angle laser light scattering','instrument','separation column');
INSERT INTO common_lookup (name,attribute,value) VALUES ('asymmetrical flow field-flow fractionation with multi-angle laser light scattering','instrument','spectrophotometer');
INSERT INTO common_lookup (name,attribute,value) VALUES ('atomic force microscopy','instrument','atomic force microscope');
INSERT INTO common_lookup (name,attribute,value) VALUES ('capillary electrophoresis','instrument','capillary electrophoresis instrument');
INSERT INTO common_lookup (name,attribute,value) VALUES ('cell counting','instrument','coulter counter');
INSERT INTO common_lookup (name,attribute,value) VALUES ('cell counting','instrument','hemocytometer');
INSERT INTO common_lookup (name,attribute,value) VALUES ('coagulation detection','instrument','coagulation monitor');
INSERT INTO common_lookup (name,attribute,value) VALUES ('colony counting','instrument','automated colony counter');
INSERT INTO common_lookup (name,attribute,value) VALUES ('confocal laser scanning microscopy','instrument','confocal microscope system');
INSERT INTO common_lookup (name,attribute,value) VALUES ('dynamic light scattering','instrument','dynamic light scattering instrument');
INSERT INTO common_lookup (name,attribute,value) VALUES ('electron microprobe analysis','instrument','electron microprobe');
INSERT INTO common_lookup (name,attribute,value) VALUES ('electrophoretic light scattering','instrument','electrophoretic light scattering instrument');
INSERT INTO common_lookup (name,attribute,value) VALUES ('energy dispersive spectroscopy','instrument','energy dispersive spectrometer');
INSERT INTO common_lookup (name,attribute,value) VALUES ('environmental transmission electron microscopy','instrument','environmental transmission electron microscope');
INSERT INTO common_lookup (name,attribute,value) VALUES ('fast protein liquid chromatography','instrument','control module');
INSERT INTO common_lookup (name,attribute,value) VALUES ('fast protein liquid chromatography','instrument','fraction collector');
INSERT INTO common_lookup (name,attribute,value) VALUES ('fast protein liquid chromatography','instrument','separation column');
INSERT INTO common_lookup (name,attribute,value) VALUES ('fast protein liquid chromatography','instrument','spectrophotometer');
INSERT INTO common_lookup (name,attribute,value) VALUES ('flow cytometry','instrument','flow cytometer');
INSERT INTO common_lookup (name,attribute,value) VALUES ('focused ion beam - scanning electron microscopy','instrument','scanning electron microscope');
INSERT INTO common_lookup (name,attribute,value) VALUES ('gas sorption','instrument','gas sorption detector');
INSERT INTO common_lookup (name,attribute,value) VALUES ('gel filtration chromatography','instrument','gel filtration column');
INSERT INTO common_lookup (name,attribute,value) VALUES ('high performance liquid chromatography','instrument','control module');
INSERT INTO common_lookup (name,attribute,value) VALUES ('high performance liquid chromatography','instrument','fraction collector');
INSERT INTO common_lookup (name,attribute,value) VALUES ('high performance liquid chromatography','instrument','separation column');
INSERT INTO common_lookup (name,attribute,value) VALUES ('high performance liquid chromatography','instrument','spectrophotometer');
INSERT INTO common_lookup (name,attribute,value) VALUES ('high resolution scanning electron microscopy','instrument','scanning electron microscope');
INSERT INTO common_lookup (name,attribute,value) VALUES ('high resolution transmission electron microscopy','instrument','transmission electron microscope');
INSERT INTO common_lookup (name,attribute,value) VALUES ('imaging','instrument','imaging system');
INSERT INTO common_lookup (name,attribute,value) VALUES ('mass quantitation','instrument','analytical balance');
INSERT INTO common_lookup (name,attribute,value) VALUES ('matrix assisted laser desorption ionisation - time of flight','instrument','maldi-tof mass spectrometer');
INSERT INTO common_lookup (name,attribute,value) VALUES ('multi-angle laser light scattering','instrument','refractometer');
INSERT INTO common_lookup (name,attribute,value) VALUES ('multi-angle laser light scattering','instrument','spectrophotometer');
INSERT INTO common_lookup (name,attribute,value) VALUES ('particle quantitation','instrument','coulter counter');
INSERT INTO common_lookup (name,attribute,value) VALUES ('particle quantitation','instrument','hemocytometer');
INSERT INTO common_lookup (name,attribute,value) VALUES ('polymerase chain reaction','instrument','thermal cycler');
INSERT INTO common_lookup (name,attribute,value) VALUES ('powder diffraction','instrument','powder diffractometer');
INSERT INTO common_lookup (name,attribute,value) VALUES ('radioactivity quantitation','instrument','scintillation counter');
INSERT INTO common_lookup (name,attribute,value) VALUES ('refractometry','instrument','refractometer');
INSERT INTO common_lookup (name,attribute,value) VALUES ('scanning auger spectrometry','instrument','scanning auger spectrometer');
INSERT INTO common_lookup (name,attribute,value) VALUES ('scanning electron microscopy','instrument','scanning electron microscope');
INSERT INTO common_lookup (name,attribute,value) VALUES ('scanning probe microscopy','instrument','scanning probe microscope');
INSERT INTO common_lookup (name,attribute,value) VALUES ('scanning tunneling  microscopy','instrument','scanning tunneling microscope');
INSERT INTO common_lookup (name,attribute,value) VALUES ('size exclusion chromatography with multi-angle laser light scattering','instrument','control module');
INSERT INTO common_lookup (name,attribute,value) VALUES ('size exclusion chromatography with multi-angle laser light scattering','instrument','photometer');
INSERT INTO common_lookup (name,attribute,value) VALUES ('size exclusion chromatography with multi-angle laser light scattering','instrument','refractometer');
INSERT INTO common_lookup (name,attribute,value) VALUES ('size exclusion chromatography with multi-angle laser light scattering','instrument','separation column');
INSERT INTO common_lookup (name,attribute,value) VALUES ('size exclusion chromatography with multi-angle laser light scattering','instrument','spectrophotometer');
INSERT INTO common_lookup (name,attribute,value) VALUES ('spectrophotometry','instrument','spectrophotometer');
INSERT INTO common_lookup (name,attribute,value) VALUES ('transmission electron microscopy','instrument','transmission electron microscope');
INSERT INTO common_lookup (name,attribute,value) VALUES ('X-ray photoelectron spectroscopy','instrument','X-ray photoelectron spectrometer');
INSERT INTO common_lookup (name,attribute,value) VALUES ('zeta potential analysis','instrument','zeta potential analyzer');
INSERT INTO common_lookup (name,attribute,value) VALUES ('antibody','isotype','IgA');
INSERT INTO common_lookup (name,attribute,value) VALUES ('antibody','isotype','IgD');
INSERT INTO common_lookup (name,attribute,value) VALUES ('antibody','isotype','IgE');
INSERT INTO common_lookup (name,attribute,value) VALUES ('antibody','isotype','IgG');
INSERT INTO common_lookup (name,attribute,value) VALUES ('antibody','isotype','IgM');
INSERT INTO common_lookup (name,attribute,value) VALUES ('instrument','manufacturer','Agilent');
INSERT INTO common_lookup (name,attribute,value) VALUES ('instrument','manufacturer','Amersham');
INSERT INTO common_lookup (name,attribute,value) VALUES ('instrument','manufacturer','Beckman/Coulter');
INSERT INTO common_lookup (name,attribute,value) VALUES ('instrument','manufacturer','Becton Dickinson');
INSERT INTO common_lookup (name,attribute,value) VALUES ('instrument','manufacturer','BioLogics');
INSERT INTO common_lookup (name,attribute,value) VALUES ('instrument','manufacturer','Biorad');
INSERT INTO common_lookup (name,attribute,value) VALUES ('instrument','manufacturer','BioTek');
INSERT INTO common_lookup (name,attribute,value) VALUES ('instrument','manufacturer','Brookhaven Instruments');
INSERT INTO common_lookup (name,attribute,value) VALUES ('instrument','manufacturer','Carl Zeiss');
INSERT INTO common_lookup (name,attribute,value) VALUES ('instrument','manufacturer','Diagnostica Stago');
INSERT INTO common_lookup (name,attribute,value) VALUES ('instrument','manufacturer','EDAX');
INSERT INTO common_lookup (name,attribute,value) VALUES ('instrument','manufacturer','Hitachi');
INSERT INTO common_lookup (name,attribute,value) VALUES ('instrument','manufacturer','JEOL');
INSERT INTO common_lookup (name,attribute,value) VALUES ('instrument','manufacturer','Kodak');
INSERT INTO common_lookup (name,attribute,value) VALUES ('instrument','manufacturer','Malvern');
INSERT INTO common_lookup (name,attribute,value) VALUES ('instrument','manufacturer','Micromeritics');
INSERT INTO common_lookup (name,attribute,value) VALUES ('instrument','manufacturer','Molecular Devices');
INSERT INTO common_lookup (name,attribute,value) VALUES ('instrument','manufacturer','Molecular Imaging');
INSERT INTO common_lookup (name,attribute,value) VALUES ('instrument','manufacturer','Philips');
INSERT INTO common_lookup (name,attribute,value) VALUES ('instrument','manufacturer','Quantachrome Instruments');
INSERT INTO common_lookup (name,attribute,value) VALUES ('instrument','manufacturer','Shimadzu');
INSERT INTO common_lookup (name,attribute,value) VALUES ('instrument','manufacturer','Tecan');
INSERT INTO common_lookup (name,attribute,value) VALUES ('instrument','manufacturer','Thermo Electron');
INSERT INTO common_lookup (name,attribute,value) VALUES ('instrument','manufacturer','Waters');
INSERT INTO common_lookup (name,attribute,value) VALUES ('instrument','manufacturer','Wyatt Technologies');
INSERT INTO common_lookup (name,attribute,value) VALUES ('imaging function','modality','bioluminescence');
INSERT INTO common_lookup (name,attribute,value) VALUES ('imaging function','modality','fluorescence');
INSERT INTO common_lookup (name,attribute,value) VALUES ('imaging function','modality','infrared');
INSERT INTO common_lookup (name,attribute,value) VALUES ('imaging function','modality','MRI');
INSERT INTO common_lookup (name,attribute,value) VALUES ('imaging function','modality','neutron scattering');
INSERT INTO common_lookup (name,attribute,value) VALUES ('imaging function','modality','PET');
INSERT INTO common_lookup (name,attribute,value) VALUES ('imaging function','modality','Raman spectroscopy');
INSERT INTO common_lookup (name,attribute,value) VALUES ('imaging function','modality','SPECT');
INSERT INTO common_lookup (name,attribute,value) VALUES ('imaging function','modality','ultrasound');
INSERT INTO common_lookup (name,attribute,value) VALUES ('imaging function','modality','X-ray');
INSERT INTO common_lookup (name,attribute,value) VALUES ('condition','name','centrifugation');
INSERT INTO common_lookup (name,attribute,value) VALUES ('condition','name','culture media');
INSERT INTO common_lookup (name,attribute,value) VALUES ('condition','name','electromagnetic radiation');
INSERT INTO common_lookup (name,attribute,value) VALUES ('condition','name','freeze thaw');
INSERT INTO common_lookup (name,attribute,value) VALUES ('condition','name','long term storage');
INSERT INTO common_lookup (name,attribute,value) VALUES ('condition','name','lyophilization');
INSERT INTO common_lookup (name,attribute,value) VALUES ('condition','name','ph');
INSERT INTO common_lookup (name,attribute,value) VALUES ('condition','name','sample concentration');
INSERT INTO common_lookup (name,attribute,value) VALUES ('condition','name','short term storage');
INSERT INTO common_lookup (name,attribute,value) VALUES ('condition','name','solvent media');
INSERT INTO common_lookup (name,attribute,value) VALUES ('condition','name','sonication');
INSERT INTO common_lookup (name,attribute,value) VALUES ('condition','name','temperature');
INSERT INTO common_lookup (name,attribute,value) VALUES ('culture media','property','media type');
INSERT INTO common_lookup (name,attribute,value) VALUES ('culture media','property','serum percentage');
INSERT INTO common_lookup (name,attribute,value) VALUES ('electromagnetic radiation','property','bandwidth');
INSERT INTO common_lookup (name,attribute,value) VALUES ('electromagnetic radiation','property','frequency');
INSERT INTO common_lookup (name,attribute,value) VALUES ('electromagnetic radiation','property','time');
INSERT INTO common_lookup (name,attribute,value) VALUES ('electromagnetic radiation','property','wavelength');
INSERT INTO common_lookup (name,attribute,value) VALUES ('long term storage','property','lyophilized');
INSERT INTO common_lookup (name,attribute,value) VALUES ('long term storage','property','time');
INSERT INTO common_lookup (name,attribute,value) VALUES ('lyophilization','property','time');
INSERT INTO common_lookup (name,attribute,value) VALUES ('lyophilization','property','time');
INSERT INTO common_lookup (name,attribute,value) VALUES ('short term storage','property','lyophilized');
INSERT INTO common_lookup (name,attribute,value) VALUES ('short term storage','property','time');
INSERT INTO common_lookup (name,attribute,value) VALUES ('solvent media','property','ion concentration');
INSERT INTO common_lookup (name,attribute,value) VALUES ('solvent media','property','ionic strength');
INSERT INTO common_lookup (name,attribute,value) VALUES ('solvent media','property','molecular formula');
INSERT INTO common_lookup (name,attribute,value) VALUES ('solvent media','property','osmolality');
INSERT INTO common_lookup (name,attribute,value) VALUES ('solvent media','property','serum percentage');
INSERT INTO common_lookup (name,attribute,value) VALUES ('solvent media','property','with serum');
INSERT INTO common_lookup (name,attribute,value) VALUES ('sonication','property','number of pulses');
INSERT INTO common_lookup (name,attribute,value) VALUES ('sonication','property','pulse duration');
INSERT INTO common_lookup (name,attribute,value) VALUES ('publication','researchArea','animal');
INSERT INTO common_lookup (name,attribute,value) VALUES ('publication','researchArea','cell line');
INSERT INTO common_lookup (name,attribute,value) VALUES ('publication','researchArea','characterization');
INSERT INTO common_lookup (name,attribute,value) VALUES ('publication','researchArea','clinical trials');
INSERT INTO common_lookup (name,attribute,value) VALUES ('publication','researchArea','in vitro');
INSERT INTO common_lookup (name,attribute,value) VALUES ('publication','researchArea','in vivo');
INSERT INTO common_lookup (name,attribute,value) VALUES ('publication','researchArea','synthesis');
INSERT INTO common_lookup (name,attribute,value) VALUES ('point of contact','role','investigator');
INSERT INTO common_lookup (name,attribute,value) VALUES ('point of contact','role','manufacturer');
INSERT INTO common_lookup (name,attribute,value) VALUES ('solubility','solvent','alcohol');
INSERT INTO common_lookup (name,attribute,value) VALUES ('solubility','solvent','phospate-buffered saline');
INSERT INTO common_lookup (name,attribute,value) VALUES ('solubility','solvent','saline');
INSERT INTO common_lookup (name,attribute,value) VALUES ('solubility','solvent','water');
INSERT INTO common_lookup (name,attribute,value) VALUES ('publication','status','in preparation');
INSERT INTO common_lookup (name,attribute,value) VALUES ('publication','status','in press');
INSERT INTO common_lookup (name,attribute,value) VALUES ('publication','status','published');
INSERT INTO common_lookup (name,attribute,value) VALUES ('publication','status','submitted');
INSERT INTO common_lookup (name,attribute,value) VALUES ('activation method','type','enzymatic cleavage');
INSERT INTO common_lookup (name,attribute,value) VALUES ('activation method','type','infrared');
INSERT INTO common_lookup (name,attribute,value) VALUES ('activation method','type','MRI');
INSERT INTO common_lookup (name,attribute,value) VALUES ('activation method','type','NMR');
INSERT INTO common_lookup (name,attribute,value) VALUES ('activation method','type','pH');
INSERT INTO common_lookup (name,attribute,value) VALUES ('activation method','type','ultrasound');
INSERT INTO common_lookup (name,attribute,value) VALUES ('activation method','type','ultraviolet');
INSERT INTO common_lookup (name,attribute,value) VALUES ('antibody','type','Fab');
INSERT INTO common_lookup (name,attribute,value) VALUES ('antibody','type','ScFv');
INSERT INTO common_lookup (name,attribute,value) VALUES ('antibody','type','whole');
INSERT INTO common_lookup (name,attribute,value) VALUES ('biopolymer','type','DNA');
INSERT INTO common_lookup (name,attribute,value) VALUES ('biopolymer','type','peptide');
INSERT INTO common_lookup (name,attribute,value) VALUES ('biopolymer','type','protein');
INSERT INTO common_lookup (name,attribute,value) VALUES ('biopolymer','type','RNA');
INSERT INTO common_lookup (name,attribute,value) VALUES ('composing element','type','coat');
INSERT INTO common_lookup (name,attribute,value) VALUES ('composing element','type','core');
INSERT INTO common_lookup (name,attribute,value) VALUES ('composing element','type','lipid');
INSERT INTO common_lookup (name,attribute,value) VALUES ('composing element','type','modifier');
INSERT INTO common_lookup (name,attribute,value) VALUES ('composing element','type','monomer');
INSERT INTO common_lookup (name,attribute,value) VALUES ('composing element','type','repeat unit');
INSERT INTO common_lookup (name,attribute,value) VALUES ('composing element','type','shell');
INSERT INTO common_lookup (name,attribute,value) VALUES ('composing element','type','terminal group');
INSERT INTO common_lookup (name,attribute,value) VALUES ('file','type','document');
INSERT INTO common_lookup (name,attribute,value) VALUES ('file','type','graph');
INSERT INTO common_lookup (name,attribute,value) VALUES ('file','type','image');
INSERT INTO common_lookup (name,attribute,value) VALUES ('file','type','spread sheet');
INSERT INTO common_lookup (name,attribute,value) VALUES ('molecular formula','type','SMARTS');
INSERT INTO common_lookup (name,attribute,value) VALUES ('molecular formula','type','SMILES');
INSERT INTO common_lookup (name,attribute,value) VALUES ('physical state','type','colloid-emulsion');
INSERT INTO common_lookup (name,attribute,value) VALUES ('physical state','type','colloid-gel');
INSERT INTO common_lookup (name,attribute,value) VALUES ('physical state','type','colloid-sol');
INSERT INTO common_lookup (name,attribute,value) VALUES ('physical state','type','fluid-gas');
INSERT INTO common_lookup (name,attribute,value) VALUES ('physical state','type','fluid-liquid');
INSERT INTO common_lookup (name,attribute,value) VALUES ('physical state','type','fluid-vapor');
INSERT INTO common_lookup (name,attribute,value) VALUES ('physical state','type','solid-crystal');
INSERT INTO common_lookup (name,attribute,value) VALUES ('physical state','type','solid-fibril');
INSERT INTO common_lookup (name,attribute,value) VALUES ('physical state','type','solid-glass');
INSERT INTO common_lookup (name,attribute,value) VALUES ('physical state','type','solid-granule');
INSERT INTO common_lookup (name,attribute,value) VALUES ('physical state','type','solid-powder');
INSERT INTO common_lookup (name,attribute,value) VALUES ('protocol','type','in vitro assay');
INSERT INTO common_lookup (name,attribute,value) VALUES ('protocol','type','in vivo assay');
INSERT INTO common_lookup (name,attribute,value) VALUES ('protocol','type','physico-chemical assay');
INSERT INTO common_lookup (name,attribute,value) VALUES ('protocol','type','radio labeling');
INSERT INTO common_lookup (name,attribute,value) VALUES ('protocol','type','safety');
INSERT INTO common_lookup (name,attribute,value) VALUES ('protocol','type','sample preparation');
INSERT INTO common_lookup (name,attribute,value) VALUES ('protocol','type','synthesis');
INSERT INTO common_lookup (name,attribute,value) VALUES ('shape','type','2D-circle');
INSERT INTO common_lookup (name,attribute,value) VALUES ('shape','type','2D-diamond');
INSERT INTO common_lookup (name,attribute,value) VALUES ('shape','type','2D-ellipse');
INSERT INTO common_lookup (name,attribute,value) VALUES ('shape','type','2D-parallelogram');
INSERT INTO common_lookup (name,attribute,value) VALUES ('shape','type','2D-polygon');
INSERT INTO common_lookup (name,attribute,value) VALUES ('shape','type','2D-rectangle');
INSERT INTO common_lookup (name,attribute,value) VALUES ('shape','type','2D-square');
INSERT INTO common_lookup (name,attribute,value) VALUES ('shape','type','2D-trapezoid');
INSERT INTO common_lookup (name,attribute,value) VALUES ('shape','type','2D-triangle');
INSERT INTO common_lookup (name,attribute,value) VALUES ('shape','type','3D-cone');
INSERT INTO common_lookup (name,attribute,value) VALUES ('shape','type','3D-cube');
INSERT INTO common_lookup (name,attribute,value) VALUES ('shape','type','3D-cylinder');
INSERT INTO common_lookup (name,attribute,value) VALUES ('shape','type','3D-disc');
INSERT INTO common_lookup (name,attribute,value) VALUES ('shape','type','3D-fibril');
INSERT INTO common_lookup (name,attribute,value) VALUES ('shape','type','3D-hexahedron');
INSERT INTO common_lookup (name,attribute,value) VALUES ('shape','type','3D-needle');
INSERT INTO common_lookup (name,attribute,value) VALUES ('shape','type','3D-oblate spheroid');
INSERT INTO common_lookup (name,attribute,value) VALUES ('shape','type','3D-polyhedron');
INSERT INTO common_lookup (name,attribute,value) VALUES ('shape','type','3D-prolate spheroid');
INSERT INTO common_lookup (name,attribute,value) VALUES ('shape','type','3D-rod');
INSERT INTO common_lookup (name,attribute,value) VALUES ('shape','type','3D-sphere');
INSERT INTO common_lookup (name,attribute,value) VALUES ('shape','type','3D-tetrahedron');
INSERT INTO common_lookup (name,attribute,value) VALUES ('shape','type','3D-tetrapod');
INSERT INTO common_lookup (name,attribute,value) VALUES ('species','type','cat');
INSERT INTO common_lookup (name,attribute,value) VALUES ('species','type','cattle');
INSERT INTO common_lookup (name,attribute,value) VALUES ('species','type','dog');
INSERT INTO common_lookup (name,attribute,value) VALUES ('species','type','goat');
INSERT INTO common_lookup (name,attribute,value) VALUES ('species','type','guinea pig');
INSERT INTO common_lookup (name,attribute,value) VALUES ('species','type','hamster');
INSERT INTO common_lookup (name,attribute,value) VALUES ('species','type','horse');
INSERT INTO common_lookup (name,attribute,value) VALUES ('species','type','human');
INSERT INTO common_lookup (name,attribute,value) VALUES ('species','type','mouse');
INSERT INTO common_lookup (name,attribute,value) VALUES ('species','type','pig');
INSERT INTO common_lookup (name,attribute,value) VALUES ('species','type','rat');
INSERT INTO common_lookup (name,attribute,value) VALUES ('species','type','sheep');
INSERT INTO common_lookup (name,attribute,value) VALUES ('species','type','yeast');
INSERT INTO common_lookup (name,attribute,value) VALUES ('species','type','zebrafish');
INSERT INTO common_lookup (name,attribute,value) VALUES ('technique','type','asymmetrical flow field-flow fractionation with multi-angle laser light scattering');
INSERT INTO common_lookup (name,attribute,value) VALUES ('technique','type','atomic force microscopy');
INSERT INTO common_lookup (name,attribute,value) VALUES ('technique','type','capillary electrophoresis');
INSERT INTO common_lookup (name,attribute,value) VALUES ('technique','type','cell counting');
INSERT INTO common_lookup (name,attribute,value) VALUES ('technique','type','coagulation detection');
INSERT INTO common_lookup (name,attribute,value) VALUES ('technique','type','colony counting');
INSERT INTO common_lookup (name,attribute,value) VALUES ('technique','type','confocal laser scanning microscopy');
INSERT INTO common_lookup (name,attribute,value) VALUES ('technique','type','dynamic light scattering');
INSERT INTO common_lookup (name,attribute,value) VALUES ('technique','type','electron microprobe analysis');
INSERT INTO common_lookup (name,attribute,value) VALUES ('technique','type','electrophoretic light scattering');
INSERT INTO common_lookup (name,attribute,value) VALUES ('technique','type','energy dispersive spectroscopy');
INSERT INTO common_lookup (name,attribute,value) VALUES ('technique','type','environmental transmission electron microscopy');
INSERT INTO common_lookup (name,attribute,value) VALUES ('technique','type','fast protein liquid chromatography');
INSERT INTO common_lookup (name,attribute,value) VALUES ('technique','type','flow cytometry');
INSERT INTO common_lookup (name,attribute,value) VALUES ('technique','type','focused ion beam - scanning electron microscopy');
INSERT INTO common_lookup (name,attribute,value) VALUES ('technique','type','gas sorption');
INSERT INTO common_lookup (name,attribute,value) VALUES ('technique','type','gel filtration chromatography');
INSERT INTO common_lookup (name,attribute,value) VALUES ('technique','type','high performance liquid chromatography');
INSERT INTO common_lookup (name,attribute,value) VALUES ('technique','type','high resolution scanning electron microscopy');
INSERT INTO common_lookup (name,attribute,value) VALUES ('technique','type','high resolution transmission electron microscopy');
INSERT INTO common_lookup (name,attribute,value) VALUES ('technique','type','imaging');
INSERT INTO common_lookup (name,attribute,value) VALUES ('technique','type','mass quantitation');
INSERT INTO common_lookup (name,attribute,value) VALUES ('technique','type','matrix assisted laser desorption ionisation - time of flight');
INSERT INTO common_lookup (name,attribute,value) VALUES ('technique','type','particle quantitation');
INSERT INTO common_lookup (name,attribute,value) VALUES ('technique','type','polymerase chain reaction');
INSERT INTO common_lookup (name,attribute,value) VALUES ('technique','type','powder diffraction');
INSERT INTO common_lookup (name,attribute,value) VALUES ('technique','type','radioactivity quantitation');
INSERT INTO common_lookup (name,attribute,value) VALUES ('technique','type','refractometry');
INSERT INTO common_lookup (name,attribute,value) VALUES ('technique','type','scanning auger spectrometry');
INSERT INTO common_lookup (name,attribute,value) VALUES ('technique','type','scanning electron microscopy');
INSERT INTO common_lookup (name,attribute,value) VALUES ('technique','type','scanning probe microscopy');
INSERT INTO common_lookup (name,attribute,value) VALUES ('technique','type','scanning tunneling  microscopy');
INSERT INTO common_lookup (name,attribute,value) VALUES ('technique','type','size exclusion chromatography with multi-angle laser light scattering');
INSERT INTO common_lookup (name,attribute,value) VALUES ('technique','type','spectrophotometry');
INSERT INTO common_lookup (name,attribute,value) VALUES ('technique','type','transmission electron microscopy');
INSERT INTO common_lookup (name,attribute,value) VALUES ('technique','type','X-ray photoelectron spectroscopy');
INSERT INTO common_lookup (name,attribute,value) VALUES ('technique','type','zeta potential analysis');
INSERT INTO common_lookup (name,attribute,value) VALUES ('LC50','unit','mg/L');
INSERT INTO common_lookup (name,attribute,value) VALUES ('LC50','unit','nmol/L');
INSERT INTO common_lookup (name,attribute,value) VALUES ('bandwidth','unit','Hz');
INSERT INTO common_lookup (name,attribute,value) VALUES ('centrifugation','unit','g-Force');
INSERT INTO common_lookup (name,attribute,value) VALUES ('centrifugation','unit','RPM');
INSERT INTO common_lookup (name,attribute,value) VALUES ('charge','unit','a.u.');
INSERT INTO common_lookup (name,attribute,value) VALUES ('charge','unit','aC');
INSERT INTO common_lookup (name,attribute,value) VALUES ('charge','unit','Ah');
INSERT INTO common_lookup (name,attribute,value) VALUES ('charge','unit','C');
INSERT INTO common_lookup (name,attribute,value) VALUES ('charge','unit','esu');
INSERT INTO common_lookup (name,attribute,value) VALUES ('charge','unit','Fr');
INSERT INTO common_lookup (name,attribute,value) VALUES ('charge','unit','statC');
INSERT INTO common_lookup (name,attribute,value) VALUES ('dimension','unit',' nm');
INSERT INTO common_lookup (name,attribute,value) VALUES ('freeze thaw','unit','number of cycles');
INSERT INTO common_lookup (name,attribute,value) VALUES ('frequency','unit','Hz');
INSERT INTO common_lookup (name,attribute,value) VALUES ('ion concentration','unit','mol/L');
INSERT INTO common_lookup (name,attribute,value) VALUES ('ionic strength','unit','mol/L');
INSERT INTO common_lookup (name,attribute,value) VALUES ('luminescence signal','unit','volt');
INSERT INTO common_lookup (name,attribute,value) VALUES ('molecular weight','unit','kDa');
INSERT INTO common_lookup (name,attribute,value) VALUES ('osmolality','unit','osmol/kg');
INSERT INTO common_lookup (name,attribute,value) VALUES ('power','unit','kilowatt');
INSERT INTO common_lookup (name,attribute,value) VALUES ('power','unit','watt');
INSERT INTO common_lookup (name,attribute,value) VALUES ('size','unit','nm');
INSERT INTO common_lookup (name,attribute,value) VALUES ('sample concentration','unit','g/mL');
INSERT INTO common_lookup (name,attribute,value) VALUES ('sample concentration','unit','mg/mL');
INSERT INTO common_lookup (name,attribute,value) VALUES ('sample concentration','unit','mg/mL');
INSERT INTO common_lookup (name,attribute,value) VALUES ('sample concentration','unit','ug/uL');
INSERT INTO common_lookup (name,attribute,value) VALUES ('surface area','unit','nm^2');
INSERT INTO common_lookup (name,attribute,value) VALUES ('temperature','unit','Celsius');
INSERT INTO common_lookup (name,attribute,value) VALUES ('temperature','unit','Fahrenheit');
INSERT INTO common_lookup (name,attribute,value) VALUES ('time','unit','day');
INSERT INTO common_lookup (name,attribute,value) VALUES ('time','unit','hour');
INSERT INTO common_lookup (name,attribute,value) VALUES ('time','unit','minute');
INSERT INTO common_lookup (name,attribute,value) VALUES ('time','unit','second');
INSERT INTO common_lookup (name,attribute,value) VALUES ('wavelength','unit','nm');
INSERT INTO common_lookup (name,attribute,value) VALUES ('zeta potential','unit','mV');
INSERT INTO common_lookup (name,attribute,value) VALUES ('datum and condition','valueType','boolean');
INSERT INTO common_lookup (name,attribute,value) VALUES ('datum and condition','valueType','mean');
INSERT INTO common_lookup (name,attribute,value) VALUES ('datum and condition','valueType','median');
INSERT INTO common_lookup (name,attribute,value) VALUES ('datum and condition','valueType','mode');
INSERT INTO common_lookup (name,attribute,value) VALUES ('datum and condition','valueType','observed');
INSERT INTO common_lookup (name,attribute,value) VALUES ('datum and condition','valueType','RMS');
INSERT INTO common_lookup (name,attribute,value) VALUES ('datum and condition','valueType','standard deviation');
INSERT INTO common_lookup (name,attribute,value) VALUES ('datum and condition','valueType','Z-score');
INSERT INTO common_lookup (name,attribute,value) VALUES ('datum and condition','valueType','Z-average');
INSERT INTO common_lookup (name,attribute,value) VALUES ('composing element','valueUnit','%');
INSERT INTO common_lookup (name,attribute,value) VALUES ('composing element','valueUnit','%mole');
INSERT INTO common_lookup (name,attribute,value) VALUES ('composing element','valueUnit','%vol');
INSERT INTO common_lookup (name,attribute,value) VALUES ('composing element','valueUnit','%wt/vol');
INSERT INTO common_lookup (name,attribute,value) VALUES ('functionalizing entity','valueUnit','%');
INSERT INTO common_lookup (name,attribute,value) VALUES ('functionalizing entity','valueUnit','%mole');
INSERT INTO common_lookup (name,attribute,value) VALUES ('functionalizing entity','valueUnit','%vol');
INSERT INTO common_lookup (name,attribute,value) VALUES ('functionalizing entity','valueUnit','%wt/vol');
INSERT INTO common_lookup (name,attribute,value) VALUES ('carbon nanotube','wallType','DWNT');
INSERT INTO common_lookup (name,attribute,value) VALUES ('carbon nanotube','wallType','MWNT');
INSERT INTO common_lookup (name,attribute,value) VALUES ('carbon nanotube','wallType','SWNT');

ALTER TABLE canano.common_lookup
 CHANGE common_lookup_pk_id common_lookup_pk_id BIGINT(20)  NOT NULL;
