function FileData_Pairs(x)
{
x.t("managing","publications");
x.t("summary","page");
x.t("submissions","edited");
x.t("descriptions","editing");
x.t("editing","publication");
x.t("editing","page");
x.t("document","submissions");
x.t("clicking","edit");
x.t("found","update");
x.t("logged","curator");
x.t("publication","managing");
x.t("publication","summary");
x.t("publication","editing");
x.t("publication","document");
x.t("publication","logged");
x.t("publication","page");
x.t("edit","publication");
x.t("edit","[publication}");
x.t("button","publication");
x.t("publications","editing");
x.t("edited","clicking");
x.t("page","descriptions");
x.t("page","found");
x.t("page","edit");
x.t("[publication}","button");
x.t("update","publication");
}
