function FileData_Pairs(x)
{
x.t("searching","publications");
x.t("managing","publications");
x.t("describes","cananolab");
x.t("discussed","section");
x.t("editing","publication");
x.t("cananolab\u2019s","publication");
x.t("features","topics");
x.t("features","associated");
x.t("overview","submitting");
x.t("publication","searching");
x.t("publication","editing");
x.t("publication","features");
x.t("cananolab","features");
x.t("publications","managing");
x.t("publications","overview");
x.t("publications","section");
x.t("section","describes");
x.t("section","include");
x.t("submitting","publication");
x.t("include","publications");
x.t("topics","discussed");
x.t("associated","cananolab\u2019s");
}
