function FileData_Pairs(x)
{
x.t("describes","link");
x.t("describes","configure");
x.t("(csm)","create");
x.t("create","users");
x.t("(upt)","describes");
x.t("preferences","topics");
x.t("user","configuring");
x.t("user","provisioning");
x.t("link","nci\u2019s");
x.t("new","user");
x.t("security","module");
x.t("configuring","new");
x.t("configuring","site");
x.t("common","security");
x.t("nci\u2019s","common");
x.t("section","describes");
x.t("section","include");
x.t("include","following");
x.t("site","preferences");
x.t("module","(csm)");
x.t("tool","(upt)");
x.t("configure","site");
x.t("provisioning","tool");
x.t("administration","section");
x.t("administration","administration");
x.t("users","user");
x.t("topics","section");
x.t("following","configuring");
}
