-- create DATUM

CREATE TABLE DATUM
(
  DATUM_PK_ID                  NUMBER           NOT NULL,
  NAME                         VARCHAR2(2000)   NOT NULL,
  VALUE                        NUMBER           NOT NULL,
  STANDARD_DEVIATION           NUMBER,
  VALUE_UNIT                   VARCHAR2(200),
  DERIVED_BIOASSAY_DATA_PK_ID  NUMBER,
  CONTROL_NAME                 VARCHAR2(200),
  CONTROL_TYPE                 VARCHAR2(100),
  LIST_INDEX                   NUMBER
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE UNIQUE INDEX PK_DATUM ON DATUM
(DATUM_PK_ID)
LOGGING
NOPARALLEL;


ALTER TABLE DATUM ADD (
  CONSTRAINT PK_DATUM PRIMARY KEY (DATUM_PK_ID));



-- create DATUM_NAME

CREATE TABLE DATUM_NAME
(
  DATUM_NAME_PK_ID  NUMBER                      NOT NULL,
  NAME              VARCHAR2(2000)              NOT NULL,
  CATEGORY_PK_ID    NUMBER                      NOT NULL,
  IS_DATUM_PARSED   NUMBER(2)                   DEFAULT 1                     NOT NULL
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE UNIQUE INDEX PK_DATUM_NAME ON DATUM_NAME
(DATUM_NAME_PK_ID)
LOGGING
NOPARALLEL;


ALTER TABLE DATUM_NAME ADD (
  CONSTRAINT PK_DATUM_NAME PRIMARY KEY (DATUM_NAME_PK_ID));


-- create DATUM_CONDITION

CREATE TABLE DATUM_CONDITION
(
  DATUM_CONDITION_PK_ID  NUMBER                 NOT NULL,
  NAME                   VARCHAR2(100)          NOT NULL,
  VALUE                  NUMBER                 NOT NULL,
  VALUE_UNIT             VARCHAR2(200)          NOT NULL,
  DATUM_PK_ID            NUMBER                 NOT NULL,
  LIST_INDEX             NUMBER
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE UNIQUE INDEX PK_DATUM_CONDITION ON DATUM_CONDITION
(DATUM_CONDITION_PK_ID)
LOGGING
NOPARALLEL;


ALTER TABLE DATUM_CONDITION ADD (
  CONSTRAINT PK_DATUM_CONDITION PRIMARY KEY (DATUM_CONDITION_PK_ID));

-- create DERIVED_BIOASSAY_DATA

CREATE TABLE DERIVED_BIOASSAY_DATA
(
  DERIVED_BIOASSAY_DATA_PK_ID  NUMBER           NOT NULL,
  CHARACTERIZATION_PK_ID       NUMBER,
  CATEGORY                     VARCHAR2(500),
  LIST_INDEX                   NUMBER
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE UNIQUE INDEX PK_DERIVED_BIOASSAY_DATA ON DERIVED_BIOASSAY_DATA
(DERIVED_BIOASSAY_DATA_PK_ID)
LOGGING
NOPARALLEL;


ALTER TABLE DERIVED_BIOASSAY_DATA ADD (
  CONSTRAINT PK_DERIVED_BIOASSAY_DATA PRIMARY KEY (DERIVED_BIOASSAY_DATA_PK_ID));


-- create KEYWORD_BIOASSAY_DATA

CREATE TABLE KEYWORD_BIOASSAY_DATA
(
  KEYWORD_PK_ID                NUMBER           NOT NULL,
  DERIVED_BIOASSAY_DATA_PK_ID  NUMBER           NOT NULL
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE UNIQUE INDEX PK_KEYWORD_BIOASSAY_DATA ON KEYWORD_BIOASSAY_DATA
(KEYWORD_PK_ID, DERIVED_BIOASSAY_DATA_PK_ID)
LOGGING
NOPARALLEL;


ALTER TABLE KEYWORD_BIOASSAY_DATA ADD (
  CONSTRAINT PK_KEYWORD_BIOASSAY_DATA PRIMARY KEY (KEYWORD_PK_ID, DERIVED_BIOASSAY_DATA_PK_ID));


-- create  PROTOCOL_FILE

CREATE TABLE PROTOCOL_FILE
(
  PROTOCOL_FILE_PK_ID  NUMBER                   NOT NULL,
  PROTOCOL_PK_ID       NUMBER                   NOT NULL
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE UNIQUE INDEX PK_PROTOCOL_FILE ON PROTOCOL_FILE
(PROTOCOL_FILE_PK_ID)
LOGGING
NOPARALLEL;




-- create INSTRUMENT_CONFIG 

CREATE TABLE INSTRUMENT_CONFIG
(
  INSTRUMENT_CONFIG_PK_ID  NUMBER               NOT NULL,
  DESCRIPTION              VARCHAR2(4000),
  INSTRUMENT_PK_ID         NUMBER               NOT NULL
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE UNIQUE INDEX PK_INSTRUMENT_CONFIG ON INSTRUMENT_CONFIG
(INSTRUMENT_CONFIG_PK_ID)
LOGGING
NOPARALLEL;




--  create Function_type

CREATE TABLE FUNCTION_TYPE
(
  FUNCTION_TYPE_PK_ID  NUMBER                   NOT NULL,
  NAME                 VARCHAR2(200)            NOT NULL
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE UNIQUE INDEX PK_FUNCTION_TYPE ON FUNCTION_TYPE
(FUNCTION_TYPE_PK_ID)
LOGGING
NOPARALLEL;


ALTER TABLE FUNCTION_TYPE ADD (
  CONSTRAINT PK_FUNCTION_TYPE PRIMARY KEY (FUNCTION_TYPE_PK_ID));


--Alter existing tables

ALTER TABLE PROTOCOL_FILE ADD (
  CONSTRAINT PK_PROTOCOL_FILE PRIMARY KEY (PROTOCOL_FILE_PK_ID));



-- alter lab_file table to add a new column
ALTER TABLE LAB_FILE
	ADD type	VARCHAR2(200);


-- alter characterization table

ALTER TABLE CHARACTERIZATION
	ADD protocol_file_pk_id	NUMBER;

ALTER TABLE CHARACTERIZATION
	ADD Instrument_config_pk_id	NUMBER;


-- alter protocol


ALTER TABLE PROTOCOL
	MODIFY (PROTOCOL_NAME	VARCHAR2(2000) )
	ADD PROTOCOL_TYPE	VARCHAR2(2000);


CREATE TABLE INSTRUMENT_TMP
(
  INSTRUMENT_PK_ID  NUMBER                 NOT NULL,
  TYPE                   VARCHAR2(200),
  ABBREVIATION           VARCHAR2(50),
  MANUFACTURER           VARCHAR2(2000)
)
LOGGING 
NOCACHE
NOPARALLEL;


ALTER TABLE INSTRUMENT_TMP ADD (
  PRIMARY KEY (INSTRUMENT_PK_ID));

CREATE TABLE BIOASSAY_DATA_CATEGORY
(
  CATEGORY_PK_ID         NUMBER                 NOT NULL,
  NAME                   VARCHAR2(2000)         NOT NULL,
  CHARACTERIZATION_NAME  VARCHAR2(2000)         NOT NULL
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE UNIQUE INDEX PK_BIOASSAY_DATA_CATEGORY ON BIOASSAY_DATA_CATEGORY
(CATEGORY_PK_ID)
LOGGING
NOPARALLEL;


ALTER TABLE BIOASSAY_DATA_CATEGORY ADD (
  CONSTRAINT PK_BIOASSAY_DATA_CATEGORY PRIMARY KEY (CATEGORY_PK_ID));

CREATE TABLE CHARACTERIZATION_CATEGORY
(
  CHAR_CATEGORY_PK_ID  NUMBER                   NOT NULL,
  CATEGORY             VARCHAR2(200)            NOT NULL,
  NAME                 VARCHAR2(200)            NOT NULL,
  HAS_ACTION           NUMBER                   NOT NULL,
  CATEGORY_ORDER       NUMBER                   NOT NULL,
  INDENT_LEVEL         NUMBER                   NOT NULL
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE UNIQUE INDEX PK_CHARACTERIZATION_CATEGORY ON CHARACTERIZATION_CATEGORY
(CHAR_CATEGORY_PK_ID)
LOGGING
NOPARALLEL;


ALTER TABLE CHARACTERIZATION_CATEGORY ADD (
  CONSTRAINT PK_CHARACTERIZATION_CATEGORY PRIMARY KEY (CHAR_CATEGORY_PK_ID));



