USE canano;

-- ----------------------------------------------------------------------
-- SQL data bulk transfer script generated by the MySQL Migration Toolkit
-- ----------------------------------------------------------------------

-- Disable foreign key checks
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;

INSERT INTO csm_group(group_name, group_desc, update_date, application_id)
VALUES ('Public', 'caBIG and public', sysdate(), 2);
VALUES ('Curator', 'Curator for the caNanoLab Data', sysdate(), 2);

INSERT INTO csm_role(role_name, role_description, application_id, active_flag, update_date)
VALUES ('R', 'read only', 2, 1, sysdate()),
  ('E', 'execute only', 2, 1, sysdate()),
  ('D', 'delete only', 2, 1, sysdate()),
  ('CUR', 'create, update, read', 2, 1, sysdate()),
  ('CURD', 'create, update, read, delete', 2, 1, sysdate());

INSERT INTO csm_role_privilege(role_id, privilege_id)
VALUES (2,7),
  (1,3),
  (3,6),
  (4,5),
  (4,1),
  (4,3),
  (5,1),
  (5,6),
  (5,3),
  (5,5);

INSERT INTO csm_user_pe(user_protection_element_id, protection_element_id, user_id)
VALUES (2, 2, 1);

INSERT INTO csm_user_group(user_group_id, user_id, group_id)
VALUES (1, 1, 1);

-- Re-enable foreign key checks
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;

-- End of script
