# Replace the <<database_name>> with proper database name that is to be created.

USE canano;

# update to csm 3.2
UPDATE csm_application SET csm_application.DECLARATIVE_FLAG='0';

ALTER TABLE CSM_PROTECTION_ELEMENT DROP COLUMN PROTECTION_ELEMENT_TYPE_ID;
ALTER TABLE CSM_PROTECTION_ELEMENT ADD COLUMN PROTECTION_ELEMENT_TYPE VARCHAR(100);
ALTER TABLE CSM_PG_PE MODIFY COLUMN UPDATE_DATE DATE;
ALTER TABLE CSM_APPLICATION MODIFY COLUMN APPLICATION_NAME VARCHAR(255) NOT NULL;
ALTER TABLE CSM_GROUP MODIFY COLUMN GROUP_NAME VARCHAR(255) NOT NULL;
ALTER TABLE CSM_PROTECTION_ELEMENT ADD UNIQUE UQ_PE_OBJECT_ID_ATTRIBUTE_APP_ID(PROTECTION_ELEMENT_NAME, ATTRIBUTE, APPLICATION_ID);

ALTER TABLE CSM_APPLICATION ADD COLUMN DATABASE_URL VARCHAR(100);
ALTER TABLE CSM_APPLICATION ADD COLUMN DATABASE_USER_NAME VARCHAR(100);
ALTER TABLE CSM_APPLICATION ADD COLUMN DATABASE_PASSWORD VARCHAR(100);
ALTER TABLE CSM_APPLICATION ADD COLUMN DATABASE_DIALECT VARCHAR(100);
ALTER TABLE CSM_APPLICATION ADD COLUMN DATABASE_DRIVER VARCHAR(100);

UPDATE csm_pg_pe SET UPDATE_DATE=NULL;

# upgrade to csm 4.0
CREATE TABLE CSM_FILTER_CLAUSE ( 
	FILTER_CLAUSE_ID BIGINT AUTO_INCREMENT  NOT NULL,
	CLASS_NAME VARCHAR(100) NOT NULL,
	FILTER_CHAIN VARCHAR(2000) NOT NULL,
	TARGET_CLASS_NAME VARCHAR (100) NOT NULL,
	TARGET_CLASS_ATTRIBUTE_NAME VARCHAR (100) NOT NULL,
	TARGET_CLASS_ATTRIBUTE_TYPE VARCHAR (100) NOT NULL,
	TARGET_CLASS_ALIAS VARCHAR (100),
	TARGET_CLASS_ATTRIBUTE_ALIAS VARCHAR (100),
	GENERATED_SQL VARCHAR (4000) NOT NULL,
	APPLICATION_ID BIGINT NOT NULL,
	UPDATE_DATE DATE NOT NULL,
	PRIMARY KEY(FILTER_CLAUSE_ID)	
)Type=InnoDB 
;
 
ALTER TABLE CSM_PROTECTION_ELEMENT ADD ( ATTRIBUTE_VALUE VARCHAR(100) );

ALTER TABLE CSM_PROTECTION_ELEMENT DROP CONSTRAINT UQ_PE_PE_NAME_ATTRIBUTE_APP_ID;
 
ALTER TABLE CSM_PROTECTION_ELEMENT ADD CONSTRAINT UQ_PE_PE_NAME_ATTRIBUTE_VALUE_APP_ID UNIQUE (OBJECT_ID, ATTRIBUTE, ATTRIBUTE_VALUE, APPLICATION_ID);

# upgrade to csm 4.1
ALTER TABLE CSM_USER MODIFY COLUMN LOGIN_NAME VARCHAR(500);
ALTER TABLE CSM_USER ADD COLUMN MIGRATED_FLAG BOOL NOT NULL DEFAULT 0;
ALTER TABLE CSM_USER ADD COLUMN PREMGRT_LOGIN_NAME VARCHAR(100) ;


ALTER TABLE CSM_PG_PE MODIFY COLUMN UPDATE_DATE DATE DEFAULT '0000-00-00';

ALTER TABLE CSM_ROLE_PRIVILEGE DROP COLUMN UPDATE_DATE;
ALTER TABLE CSM_USER_PE DROP COLUMN UPDATE_DATE;

ALTER TABLE CSM_FILTER_CLAUSE CHANGE GENERATED_SQL GENERATED_SQL_USER VARCHAR (4000) NOT NULL;
ALTER TABLE CSM_FILTER_CLAUSE ADD COLUMN GENERATED_SQL_GROUP VARCHAR (4000) NOT NULL;

