function FileData_Pairs(x)
{
x.t("working","calab");
x.t("assay","run.");
x.t("assay","run");
x.t("creating","assay");
x.t("aliquot","aliquot");
x.t("aliquot","calab");
x.t("aliquot","include");
x.t("aliquot","using");
x.t("part","assay");
x.t("executing","calab");
x.t("calab","executing");
x.t("calab","workflow");
x.t("calab","online");
x.t("workflow","using");
x.t("run.","information");
x.t("include","part");
x.t("online","help");
x.t("help","working");
x.t("information","creating");
x.t("using","aliquot");
}
