function FileData_Pairs(x)
{
x.t("managing","samples");
x.t("deleting","sample");
x.t("copying","existing");
x.t("sample","managing");
x.t("sample","deleting");
x.t("sample","editing");
x.t("sample","edit");
x.t("sample","updating");
x.t("sample","using");
x.t("sample","adding");
x.t("editing","sample");
x.t("edit","sample");
x.t("updating","sample");
x.t("techniques","copying");
x.t("publications","sample");
x.t("samples","editing");
x.t("existing","sample");
x.t("following","techniques");
x.t("using","following");
x.t("adding","publications");
}
