USE canano;

ALTER TABLE canano.common_lookup
 CHANGE common_lookup_pk_id common_lookup_pk_id BIGINT(20) AUTO_INCREMENT NOT NULL;

insert into common_lookup(name,attribute,value) values ('Attachment','bondType','covalent');
insert into common_lookup(name,attribute,value) values ('Attachment','bondType','electrostatic');
insert into common_lookup(name,attribute,value) values ('Attachment','bondType','hydrogen');
insert into common_lookup(name,attribute,value) values ('Attachment','bondType','ionic');
insert into common_lookup(name,attribute,value) values ('Attachment','bondType','van der Waals');

insert into common_lookup(name,attribute,value) values ('Cytotoxicity','cellLine','human hepatocarinoma');
insert into common_lookup(name,attribute,value) values ('Cytotoxicity','cellLine','porcine renal tubule');

insert into common_lookup(name,attribute,value) values ('Emulsion','composingElementType','bulk phase');
insert into common_lookup(name,attribute,value) values ('Emulsion','composingElementType','dispersed phase');
insert into common_lookup(name,attribute,value) values ('Emulsion','composingElementType','emulsifier');

insert into common_lookup(name,attribute,value) values ('Antibody','displayName','antibody');
insert into common_lookup(name,attribute,value) values ('Antigen','displayName','antigen');
insert into common_lookup(name,attribute,value) values ('Attachment','displayName','attachment');
insert into common_lookup(name,attribute,value) values ('Biopolymer','displayName','biopolymer');
insert into common_lookup(name,attribute,value) values ('BloodContact','displayName','Blood Contact');
insert into common_lookup(name,attribute,value) values ('CarbonNanotube','displayName','carbon nanotube');
insert into common_lookup(name,attribute,value) values ('Cytotoxicity','displayName','Cytotoxicity');
insert into common_lookup(name,attribute,value) values ('Dendrimer','displayName','dendrimer');
insert into common_lookup(name,attribute,value) values ('Emulsion','displayName','emulsion');
insert into common_lookup(name,attribute,value) values ('Encapsulation','displayName','encapsulation');
insert into common_lookup(name,attribute,value) values ('Entrapment','displayName','entrapment');
insert into common_lookup(name,attribute,value) values ('EnzymeInduction','displayName','Enzyme Induction');
insert into common_lookup(name,attribute,value) values ('Fullerene','displayName','fullerene');
insert into common_lookup(name,attribute,value) values ('Gene','displayName','gene');
insert into common_lookup(name,attribute,value) values ('ImagingFunction','displayName','imaging');
insert into common_lookup(name,attribute,value) values ('ImmuneCellFunction','displayName','Immune Cell Function');
insert into common_lookup(name,attribute,value) values ('InvitroCharacterization','displayName','In Vitro Characterization');
insert into common_lookup(name,attribute,value) values ('InvivoCharacterization','displayName','In Vivo Characterization');
insert into common_lookup(name,attribute,value) values ('Pharmacokinetics','displayName','Pharmacokinetics');
insert into common_lookup(name,attribute,value) values ('Toxicology','displayName','Toxicology');
insert into common_lookup(name,attribute,value) values ('Liposome','displayName','liposome');
insert into common_lookup(name,attribute,value) values ('MetalParticle','displayName','metal particle');
insert into common_lookup(name,attribute,value) values ('MolecularWeight','displayName','Molecular Weight');
insert into common_lookup(name,attribute,value) values ('OxidativeStress','displayName','Oxidative Stress');
insert into common_lookup(name,attribute,value) values ('Phagocytosis','displayName','Phagocytosis');
insert into common_lookup(name,attribute,value) values ('PhysicoChemicalCharacterization','displayName','Physico-Chemical Characterization');
insert into common_lookup(name,attribute,value) values ('PhysicalState','displayName','Physical State');
insert into common_lookup(name,attribute,value) values ('Polymer','displayName','polymer');
insert into common_lookup(name,attribute,value) values ('Purity','displayName','Purity');
insert into common_lookup(name,attribute,value) values ('QuantumDot','displayName','quantum dot');
insert into common_lookup(name,attribute,value) values ('Receptor','displayName','receptor');
insert into common_lookup(name,attribute,value) values ('Shape','displayName','Shape');
insert into common_lookup(name,attribute,value) values ('Size','displayName','Size');
insert into common_lookup(name,attribute,value) values ('SmallMolecule','displayName','small molecule');
insert into common_lookup(name,attribute,value) values ('Solubility','displayName','Solubility');
insert into common_lookup(name,attribute,value) values ('Surface','displayName','Surface');
insert into common_lookup(name,attribute,value) values ('TargetingFunction','displayName','targeting');
insert into common_lookup(name,attribute,value) values ('TherapeuticFunction','displayName','therapeutic');

insert into common_lookup(name,attribute,value) values ('Antibody','isotype','IgA');
insert into common_lookup(name,attribute,value) values ('Antibody','isotype','IgD');
insert into common_lookup(name,attribute,value) values ('Antibody','isotype','IgE');
insert into common_lookup(name,attribute,value) values ('Antibody','isotype','IgG');
insert into common_lookup(name,attribute,value) values ('Antibody','isotype','IgM');

insert into common_lookup(name,attribute,value) values ('ImagingFunction','modality','bioluminescence');
insert into common_lookup(name,attribute,value) values ('ImagingFunction','modality','fluorescence');
insert into common_lookup(name,attribute,value) values ('ImagingFunction','modality','infrared');
insert into common_lookup(name,attribute,value) values ('ImagingFunction','modality','MRI');
insert into common_lookup(name,attribute,value) values ('ImagingFunction','modality','neutron scattering');
insert into common_lookup(name,attribute,value) values ('ImagingFunction','modality','PET');
insert into common_lookup(name,attribute,value) values ('ImagingFunction','modality','Raman spectroscopy');
insert into common_lookup(name,attribute,value) values ('ImagingFunction','modality','SPECT');
insert into common_lookup(name,attribute,value) values ('ImagingFunction','modality','ultrasound');
insert into common_lookup(name,attribute,value) values ('ImagingFunction','modality','X-ray');

insert into common_lookup(name,attribute,value) values ('ComposingElement','molecularFormulaType','SMARTS');
insert into common_lookup(name,attribute,value) values ('ComposingElement','molecularFormulaType','SMILES');

insert into common_lookup(name,attribute,value) values ('FunctionalizingEntity','molecularFormulaType','SMARTS');
insert into common_lookup(name,attribute,value) values ('FunctionalizingEntity','molecularFormulaType','SMILES');

insert into common_lookup(name,attribute,value) values ('Solubility','solvent','alcohol');
insert into common_lookup(name,attribute,value) values ('Solubility','solvent','phospate-buffered saline');
insert into common_lookup(name,attribute,value) values ('Solubility','solvent','saline');
insert into common_lookup(name,attribute,value) values ('Solubility','solvent','water');

insert into common_lookup(name,attribute,value) values ('Antibody','species','cat');
insert into common_lookup(name,attribute,value) values ('Antibody','species','cattle');
insert into common_lookup(name,attribute,value) values ('Antibody','species','dog');
insert into common_lookup(name,attribute,value) values ('Antibody','species','goat');
insert into common_lookup(name,attribute,value) values ('Antibody','species','guinea pig');
insert into common_lookup(name,attribute,value) values ('Antibody','species','hamster');
insert into common_lookup(name,attribute,value) values ('Antibody','species','horse');
insert into common_lookup(name,attribute,value) values ('Antibody','species','human');
insert into common_lookup(name,attribute,value) values ('Antibody','species','mouse');
insert into common_lookup(name,attribute,value) values ('Antibody','species','pig');
insert into common_lookup(name,attribute,value) values ('Antibody','species','rat');
insert into common_lookup(name,attribute,value) values ('Antibody','species','sheep');
insert into common_lookup(name,attribute,value) values ('Antibody','species','yeast');
insert into common_lookup(name,attribute,value) values ('Antibody','species','zebrafish');
insert into common_lookup(name,attribute,value) values ('Antigen','species','cat');
insert into common_lookup(name,attribute,value) values ('Antigen','species','cattle');
insert into common_lookup(name,attribute,value) values ('Antigen','species','dog');
insert into common_lookup(name,attribute,value) values ('Antigen','species','goat');
insert into common_lookup(name,attribute,value) values ('Antigen','species','guinea pig');
insert into common_lookup(name,attribute,value) values ('Antigen','species','hamster');
insert into common_lookup(name,attribute,value) values ('Antigen','species','horse');
insert into common_lookup(name,attribute,value) values ('Antigen','species','human');
insert into common_lookup(name,attribute,value) values ('Antigen','species','mouse');
insert into common_lookup(name,attribute,value) values ('Antigen','species','pig');
insert into common_lookup(name,attribute,value) values ('Antigen','species','rat');
insert into common_lookup(name,attribute,value) values ('Antigen','species','sheep');
insert into common_lookup(name,attribute,value) values ('Antigen','species','yeast');
insert into common_lookup(name,attribute,value) values ('Antigen','species','zebrafish');

insert into common_lookup(name,attribute,value) values ('ActivationMethod','type','enzymatic cleavage');
insert into common_lookup(name,attribute,value) values ('ActivationMethod','type','infrared');
insert into common_lookup(name,attribute,value) values ('ActivationMethod','type','MRI');
insert into common_lookup(name,attribute,value) values ('ActivationMethod','type','NMR');
insert into common_lookup(name,attribute,value) values ('ActivationMethod','type','pH');
insert into common_lookup(name,attribute,value) values ('ActivationMethod','type','ultrasound');
insert into common_lookup(name,attribute,value) values ('ActivationMethod','type','ultraviolet');

insert into common_lookup(name,attribute,value) values ('Antibody','type','Fab');
insert into common_lookup(name,attribute,value) values ('Antibody','type','ScFv');
insert into common_lookup(name,attribute,value) values ('Antibody','type','whole');
insert into common_lookup(name,attribute,value) values ('Biopolymer','type','DNA');
insert into common_lookup(name,attribute,value) values ('Biopolymer','type','peptide');
insert into common_lookup(name,attribute,value) values ('Biopolymer','type','protein');
insert into common_lookup(name,attribute,value) values ('Biopolymer','type','RNA');

insert into common_lookup(name,attribute,value) values ('ComposingElement','type','coat');
insert into common_lookup(name,attribute,value) values ('ComposingElement','type','core');
insert into common_lookup(name,attribute,value) values ('ComposingElement','type','modifier');
insert into common_lookup(name,attribute,value) values ('ComposingElement','type','monomer');
insert into common_lookup(name,attribute,value) values ('ComposingElement','type','lipid');
insert into common_lookup(name,attribute,value) values ('ComposingElement','type','repeat unit');
insert into common_lookup(name,attribute,value) values ('ComposingElement','type','shell');
insert into common_lookup(name,attribute,value) values ('ComposingElement','type','terminal group');

insert into common_lookup(name,attribute,value) values ('File','type','document');
insert into common_lookup(name,attribute,value) values ('File','type','graph');
insert into common_lookup(name,attribute,value) values ('File','type','image');
insert into common_lookup(name,attribute,value) values ('File','type','spread sheet');

insert into common_lookup(name,attribute,value) values ('PhysicalState','type','colloid-emulsion');
insert into common_lookup(name,attribute,value) values ('PhysicalState','type','colloid-gel');
insert into common_lookup(name,attribute,value) values ('PhysicalState','type','colloid-sol');
insert into common_lookup(name,attribute,value) values ('PhysicalState','type','fluid-gas');
insert into common_lookup(name,attribute,value) values ('PhysicalState','type','fluid-liquid');
insert into common_lookup(name,attribute,value) values ('PhysicalState','type','fluid-vapor');
insert into common_lookup(name,attribute,value) values ('PhysicalState','type','solid-crystal');
insert into common_lookup(name,attribute,value) values ('PhysicalState','type','solid-glass');
insert into common_lookup(name,attribute,value) values ('PhysicalState','type','solid-granule');
insert into common_lookup(name,attribute,value) values ('PhysicalState','type','solid-powder');
insert into common_lookup(name,attribute,value) values ('PhysicalState','type','solid-fibril');

insert into common_lookup(name,attribute,value) values ('Protocol','type','in vitro assay');
insert into common_lookup(name,attribute,value) values ('Protocol','type','in vivo assay');
insert into common_lookup(name,attribute,value) values ('Protocol','type','physico-chemical assay');
insert into common_lookup(name,attribute,value) values ('Protocol','type','radio labeling');
insert into common_lookup(name,attribute,value) values ('Protocol','type','safety');
insert into common_lookup(name,attribute,value) values ('Protocol','type','sample preparation');
insert into common_lookup(name,attribute,value) values ('Protocol','type','synthesis');

insert into common_lookup(name,attribute,value) values ('Shape','type','2D-circle');
insert into common_lookup(name,attribute,value) values ('Shape','type','2D-diamond');
insert into common_lookup(name,attribute,value) values ('Shape','type','2D-ellipse');
insert into common_lookup(name,attribute,value) values ('Shape','type','2D-parallelogram');
insert into common_lookup(name,attribute,value) values ('Shape','type','2D-polygon');
insert into common_lookup(name,attribute,value) values ('Shape','type','2D-retangle');
insert into common_lookup(name,attribute,value) values ('Shape','type','2D-square');
insert into common_lookup(name,attribute,value) values ('Shape','type','2D-trapezoid');
insert into common_lookup(name,attribute,value) values ('Shape','type','2D-triangle');
insert into common_lookup(name,attribute,value) values ('Shape','type','3D-cone');
insert into common_lookup(name,attribute,value) values ('Shape','type','3D-cube');
insert into common_lookup(name,attribute,value) values ('Shape','type','3D-cylinder');
insert into common_lookup(name,attribute,value) values ('Shape','type','3D-disc');
insert into common_lookup(name,attribute,value) values ('Shape','type','3D-fibril');
insert into common_lookup(name,attribute,value) values ('Shape','type','3D-hexahedron');
insert into common_lookup(name,attribute,value) values ('Shape','type','3D-needle');
insert into common_lookup(name,attribute,value) values ('Shape','type','3D-oblate spheroid');
insert into common_lookup(name,attribute,value) values ('Shape','type','3D-polyhedron');
insert into common_lookup(name,attribute,value) values ('Shape','type','3D-prolate spheroid');
insert into common_lookup(name,attribute,value) values ('Shape','type','3D-rod');
insert into common_lookup(name,attribute,value) values ('Shape','type','3D-sphere');
insert into common_lookup(name,attribute,value) values ('Shape','type','3D-tetrahedron');
insert into common_lookup(name,attribute,value) values ('Shape','type','3D-tetrapod');

insert into common_lookup(name,attribute,value) values ('DatumCondition','valueType','boolean');
insert into common_lookup(name,attribute,value) values ('DatumCondition','valueType','mean');
insert into common_lookup(name,attribute,value) values ('DatumCondition','valueType','median');
insert into common_lookup(name,attribute,value) values ('DatumCondition','valueType','mode');
insert into common_lookup(name,attribute,value) values ('DatumCondition','valueType','observed');
insert into common_lookup(name,attribute,value) values ('DatumCondition','valueType','standard deviation');
insert into common_lookup(name,attribute,value) values ('DatumCondition','valueType','Z-score');

insert into common_lookup(name,attribute,value) values ('ComposingElement','valueUnit','%');
insert into common_lookup(name,attribute,value) values ('ComposingElement','valueUnit','%mole');
insert into common_lookup(name,attribute,value) values ('ComposingElement','valueUnit','%vol');
insert into common_lookup(name,attribute,value) values ('ComposingElement','valueUnit','%wt/vol');

insert into common_lookup(name,attribute,value) values ('FunctionalizingEntity','valueUnit','%');
insert into common_lookup(name,attribute,value) values ('FunctionalizingEntity','valueUnit','%mole');
insert into common_lookup(name,attribute,value) values ('FunctionalizingEntity','valueUnit','%vol');
insert into common_lookup(name,attribute,value) values ('FunctionalizingEntity','valueUnit','%wt/vol');

insert into common_lookup(name,attribute,value) values ('CarbonNanotube','wallType','DWNT');
insert into common_lookup(name,attribute,value) values ('CarbonNanotube','wallType','MWNT');
insert into common_lookup(name,attribute,value) values ('CarbonNanotube','wallType','SWNT');

insert into common_lookup(name,attribute,value) values ('Publication','category','peer review article');
insert into common_lookup(name,attribute,value) values ('Publication','category','report');
insert into common_lookup(name,attribute,value) values ('Publication','category','book chapter');
insert into common_lookup(name,attribute,value) values ('Publication','category','review');
insert into common_lookup(name,attribute,value) values ('Publication','category','editorial');
insert into common_lookup(name,attribute,value) values ('Publication','category','proceeding');

insert into common_lookup(name,attribute,value) values ('Publication','status','published');
insert into common_lookup(name,attribute,value) values ('Publication','status','in press');
insert into common_lookup(name,attribute,value) values ('Publication','status','submitted');
insert into common_lookup(name,attribute,value) values ('Publication','status','in preparation');

insert into common_lookup(name,attribute,value) values ('Publication','researchArea','synthesis');
insert into common_lookup(name,attribute,value) values ('Publication','researchArea','characterization');
insert into common_lookup(name,attribute,value) values ('Publication','researchArea','cell line');
insert into common_lookup(name,attribute,value) values ('Publication','researchArea','animal');
insert into common_lookup(name,attribute,value) values ('Publication','researchArea','in vitro');
insert into common_lookup(name,attribute,value) values ('Publication','researchArea','in vivo');
insert into common_lookup(name,attribute,value) values ('Publication','researchArea','clinical trials');

insert into common_lookup(name,attribute,value) values ('PointOfContact','role','Manufacturer');
insert into common_lookup(name,attribute,value) values ('PointOfContact','role','Investigator');

insert into common_lookup (name, attribute, value) values ('Technique', 'type', 'Asymmetrical Flow Field-Flow Fractionation with Multi-Angle Laser Light Scattering');
insert into common_lookup (name, attribute, value) values ('Technique', 'type', 'Atomic Force Microscopy');
insert into common_lookup (name, attribute, value) values ('Technique', 'type', 'Capillary Electrophoresis');
insert into common_lookup (name, attribute, value) values ('Technique', 'type', 'Cell Counting');
insert into common_lookup (name, attribute, value) values ('Technique', 'type', 'Coagulation Detection');
insert into common_lookup (name, attribute, value) values ('Technique', 'type', 'Confocal Laser Scanning Microscopy');
insert into common_lookup (name, attribute, value) values ('Technique', 'type', 'Colony Counting');
insert into common_lookup (name, attribute, value) values ('Technique', 'type', 'Dynamic Light Scattering');
insert into common_lookup (name, attribute, value) values ('Technique', 'type', 'Electron Microprobe Analysis');
insert into common_lookup (name, attribute, value) values ('Technique', 'type', 'Electrophoretic Light Scattering');
insert into common_lookup (name, attribute, value) values ('Technique', 'type', 'Energy Dispersive Spectroscopy');
insert into common_lookup (name, attribute, value) values ('Technique', 'type', 'Environmental Transmission Electron Microscopy');
insert into common_lookup (name, attribute, value) values ('Technique', 'type', 'Fast Protein Liquid Chromatography');
insert into common_lookup (name, attribute, value) values ('Technique', 'type', 'Flow Cytometry');
insert into common_lookup (name, attribute, value) values ('Technique', 'type', 'Focused Ion Beam - Scanning Electron Microscopy');
insert into common_lookup (name, attribute, value) values ('Technique', 'type', 'Gas Sorption');
insert into common_lookup (name, attribute, value) values ('Technique', 'type', 'Gel Filtration Chromatography');
insert into common_lookup (name, attribute, value) values ('Technique', 'type', 'High Performance Liquid Chromatography');
insert into common_lookup (name, attribute, value) values ('Technique', 'type', 'High Resolution Scanning Electron Microscopy');
insert into common_lookup (name, attribute, value) values ('Technique', 'type', 'High Resolution Transmission Electron Microscopy');
insert into common_lookup (name, attribute, value) values ('Technique', 'type', 'Imaging');
insert into common_lookup (name, attribute, value) values ('Technique', 'type', 'Mass Quantitation');
insert into common_lookup (name, attribute, value) values ('Technique', 'type', 'Matrix Assisted Laser Desorption Ionisation - Time Of Flight');
insert into common_lookup (name, attribute, value) values ('Technique', 'type', 'Microplate Analysis');
insert into common_lookup (name, attribute, value) values ('Technique', 'type', 'Particle Quantitation');
insert into common_lookup (name, attribute, value) values ('Technique', 'type', 'Polymerase Chain Reaction');
insert into common_lookup (name, attribute, value) values ('Technique', 'type', 'Powder Diffraction');
insert into common_lookup (name, attribute, value) values ('Technique', 'type', 'Radiation Quantiation');
insert into common_lookup (name, attribute, value) values ('Technique', 'type', 'Refractometry');
insert into common_lookup (name, attribute, value) values ('Technique', 'type', 'Scanning Auger Spectrometry');
insert into common_lookup (name, attribute, value) values ('Technique', 'type', 'Scanning Electron Microscopy');
insert into common_lookup (name, attribute, value) values ('Technique', 'type', 'Scanning Probe Microscopy');
insert into common_lookup (name, attribute, value) values ('Technique', 'type', 'Scanning Tunneling  Microscopy');
insert into common_lookup (name, attribute, value) values ('Technique', 'type', 'Size Exclusion Chromatography with Multi-Angle Laser Light Scattering');
insert into common_lookup (name, attribute, value) values ('Technique', 'type', 'Spectrophotometry');
insert into common_lookup (name, attribute, value) values ('Technique', 'type', 'Transmission Electron Microscopy');
insert into common_lookup (name, attribute, value) values ('Technique', 'type', 'X-Ray Photoelectron Spectroscopy');
insert into common_lookup (name, attribute, value) values ('Technique', 'type', 'Zeta Potential Analysis');

insert into common_lookup (name, attribute, value) values ('Asymmetrical Flow Field-Flow Fractionation with Multi-Angle Laser Light Scattering','abbreviation', 'AFFF-MALLS');
insert into common_lookup (name, attribute, value) values ('Atomic Force Microscopy','abbreviation','AFM');
insert into common_lookup (name, attribute, value) values ('Confocal Laser Scanning Microscopy','abbreviation','CLSM');
insert into common_lookup (name, attribute, value) values ('Dynamic Light Scattering','abbreviation','DLS');
insert into common_lookup (name, attribute, value) values ('Electron Microprobe Analysis','abbreviation','EMPA');
insert into common_lookup (name, attribute, value) values ('Energy Dispersive Spectroscopy','abbreviation','EDS');
insert into common_lookup (name, attribute, value) values ('Environmental Transmission Electron Microscopy','abbreviation','ETEM');
insert into common_lookup (name, attribute, value) values ('Focused Ion Beam - Scanning Electron Microscopy','abbreviation','FIB-SEM');
insert into common_lookup (name, attribute, value) values ('High Performance Liquid Chromatography','abbreviation','HPLC');
insert into common_lookup (name, attribute, value) values ('High Resolution Scanning Electron Microscopy','abbreviation','HR-SEM');
insert into common_lookup (name, attribute, value) values ('High Resolution Transmission Electron Microscopy','abbreviation','HRTEM');
insert into common_lookup (name, attribute, value) values ('Matrix Assisted Laser Desorption Ionisation - Time Of Flight','abbreviation','MALDI-TOF');
insert into common_lookup (name, attribute, value) values ('Polymerase Chain Reaction','abbreviation','PCR');
insert into common_lookup (name, attribute, value) values ('Scanning Auger Spectrometry','abbreviation','SAM');
insert into common_lookup (name, attribute, value) values ('Scanning Electron Microscopy','abbreviation','SEM');
insert into common_lookup (name, attribute, value) values ('Scanning Probe Microscopy ','abbreviation','SPM');
insert into common_lookup (name, attribute, value) values ('Scanning Tunneling  Microscopy','abbreviation','STM');
insert into common_lookup (name, attribute, value) values ('Size Exclusion Chromatography with Multi-Angle Laser Light Scattering','abbreviation','SEC-MALLS');
insert into common_lookup (name, attribute, value) values ('Transmission Electron Microscopy','abbreviation','TEM');
insert into common_lookup (name, attribute, value) values ('X-Ray Photoelectron Spectroscopy','abbreviation','XPS');
insert into common_lookup (name, attribute, value) values ('Gel Filtration Chromatography','abbreviation','GFC');
insert into common_lookup (name, attribute, value) values ('Fast Protein Liquid Chromatography','abbreviation','FPLC');

insert into common_lookup (name, attribute, value) values ('Asymmetrical Flow Field-Flow Fractionation with Multi-Angle Laser Light Scattering','instrument','Photometer');
insert into common_lookup (name, attribute, value) values ('Asymmetrical Flow Field-Flow Fractionation with Multi-Angle Laser Light Scattering','instrument','Refractometer');
insert into common_lookup (name, attribute, value) values ('Asymmetrical Flow Field-Flow Fractionation with Multi-Angle Laser Light Scattering','instrument','Separation Column');
insert into common_lookup (name, attribute, value) values ('Asymmetrical Flow Field-Flow Fractionation with Multi-Angle Laser Light Scattering','instrument','Spectrophotometer');
insert into common_lookup (name, attribute, value) values ('Asymmetrical Flow Field-Flow Fractionation with Multi-Angle Laser Light Scattering','instrument','Control Module');
insert into common_lookup (name, attribute, value) values ('Atomic Force Microscopy','instrument','Atomic Force Microscope');
insert into common_lookup (name, attribute, value) values ('Capillary Electrophoresis','instrument','Capillary Electrophoresis Instrument');
insert into common_lookup (name, attribute, value) values ('Cell Counting','instrument','Hemocytometer');
insert into common_lookup (name, attribute, value) values ('Cell Counting','instrument','Coulter Counter');
insert into common_lookup (name, attribute, value) values ('Colony Counting','instrument','Automated Colony Counter');
insert into common_lookup (name, attribute, value) values ('Dynamic Light Scattering','instrument','Dynamic Light Scattering Instrument');
insert into common_lookup (name, attribute, value) values ('Electron Microprobe Analysis','instrument','Electron Microprobe');
insert into common_lookup (name, attribute, value) values ('Electrophoretic Light Scattering','instrument','Electrophoretic Light Scattering Instrument');
insert into common_lookup (name, attribute, value) values ('Energy Dispersive Spectroscopy','instrument','Energy Dispersive Spectrometer');
insert into common_lookup (name, attribute, value) values ('Environmental Transmission Electron Microscopy','instrument','Environmental Transmission Electron Microscope');
insert into common_lookup (name, attribute, value) values ('Coagulation Detection','instrument','Coagulation Monitor');
insert into common_lookup (name, attribute, value) values ('Gas Sorption','instrument','Surface Area and Pore Size Analyzer');
insert into common_lookup (name, attribute, value) values ('Flow Cytometry','instrument','Flow Cytometer');
insert into common_lookup (name, attribute, value) values ('Focused Ion Beam - Scanning Electron Microscopy','instrument','Scanning Electron Microscope');
insert into common_lookup (name, attribute, value) values ('High Performance Liquid Chromatography','instrument','Separation Column');
insert into common_lookup (name, attribute, value) values ('High Performance Liquid Chromatography','instrument','Spectrophotometer');
insert into common_lookup (name, attribute, value) values ('High Performance Liquid Chromatography','instrument','Control Module');
insert into common_lookup (name, attribute, value) values ('High Performance Liquid Chromatography','instrument','Fraction Collector');
insert into common_lookup (name, attribute, value) values ('High Resolution Scanning Electron Microscopy','instrument','Scanning Electron Microscope');
insert into common_lookup (name, attribute, value) values ('High Resolution Transmission Electron Microscopy','instrument','Transmission Electron Microscope');
insert into common_lookup (name, attribute, value) values ('Imaging','instrument','Imaging System');
insert into common_lookup (name, attribute, value) values ('Particle Quantitation','instrument','Hemocytometer');
insert into common_lookup (name, attribute, value) values ('Particle Quantitation','instrument','Coulter Counter');
insert into common_lookup (name, attribute, value) values ('Polymerase Chain Reaction','instrument','Thermal Cycler');
insert into common_lookup (name, attribute, value) values ('Powder Diffraction','instrument','Powder Diffractometer');
insert into common_lookup (name, attribute, value) values ('Radiation Quantiation','instrument','Scintillation Counter');
insert into common_lookup (name, attribute, value) values ('Refractometry','instrument','Refractometer');
insert into common_lookup (name, attribute, value) values ('Scanning Auger Spectrometry','instrument','Scanning Auger Spectrometer');
insert into common_lookup (name, attribute, value) values ('Scanning Electron Microscopy','instrument','Scanning Electron Microscope');
insert into common_lookup (name, attribute, value) values ('Scanning Probe Microscopy','instrument','Scanning Probe Microscope');
insert into common_lookup (name, attribute, value) values ('Scanning Tunneling  Microscopy','instrument','Scanning Tunneling Microscope');
insert into common_lookup (name, attribute, value) values ('Size Exclusion Chromatography with Multi-Angle Laser Light Scattering','instrument','Photometer');
insert into common_lookup (name, attribute, value) values ('Size Exclusion Chromatography with Multi-Angle Laser Light Scattering','instrument','Refractometer');
insert into common_lookup (name, attribute, value) values ('Size Exclusion Chromatography with Multi-Angle Laser Light Scattering','instrument','Separation Column');
insert into common_lookup (name, attribute, value) values ('Size Exclusion Chromatography with Multi-Angle Laser Light Scattering','instrument','Spectrophotometer');
insert into common_lookup (name, attribute, value) values ('Size Exclusion Chromatography with Multi-Angle Laser Light Scattering','instrument','Control Module');
insert into common_lookup (name, attribute, value) values ('Spectrophotometry','instrument','Spectrophotometer');
insert into common_lookup (name, attribute, value) values ('Transmission Electron Microscopy','instrument','Transmission Electron Microscope');
insert into common_lookup (name, attribute, value) values ('X-Ray Photoelectron Spectroscopy','instrument','X-Ray Photoelectron Spectrometer');
insert into common_lookup (name, attribute, value) values ('Microplate Analysis','instrument','Microplate Reader');
insert into common_lookup (name, attribute, value) values ('Matrix Assisted Laser Desorption Ionisation - Time Of Flight','instrument','MALDI-TOF Mass Spectrometer');
insert into common_lookup (name, attribute, value) values ('Confocal Laser Scanning Microscopy','instrument','Confocal Microscope');
insert into common_lookup (name, attribute, value) values ('Zeta Potential Analysis','instrument','Zeta Potential Analyzer');
insert into common_lookup (name, attribute, value) values ('Fast Protein Liquid Chromatography','instrument','Separation Column');
insert into common_lookup (name, attribute, value) values ('Fast Protein Liquid Chromatography','instrument','Spectrophotometer');
insert into common_lookup (name, attribute, value) values ('Fast Protein Liquid Chromatography','instrument','Control Module');
insert into common_lookup (name, attribute, value) values ('Fast Protein Liquid Chromatography','instrument','Fraction Collector');
insert into common_lookup (name, attribute, value) values ('Mass Quantitation','instrument','Analytical Balance');
insert into common_lookup (name, attribute, value) values ('Gel Filtration Chromatography','instrument','Gel Filtration Column');

insert into common_lookup (name, attribute, value) values ('Instrument', 'manufacturer', 'Agilent');
insert into common_lookup (name, attribute, value) values ('Instrument', 'manufacturer', 'Amersham');
insert into common_lookup (name, attribute, value) values ('Instrument', 'manufacturer', 'Beckman/Coulter');
insert into common_lookup (name, attribute, value) values ('Instrument', 'manufacturer', 'Becton Dickinson');
insert into common_lookup (name, attribute, value) values ('Instrument', 'manufacturer', 'BioLogics');
insert into common_lookup (name, attribute, value) values ('Instrument', 'manufacturer', 'Biorad');
insert into common_lookup (name, attribute, value) values ('Instrument', 'manufacturer', 'BioTek');
insert into common_lookup (name, attribute, value) values ('Instrument', 'manufacturer', 'Brookhaven Instruments');
insert into common_lookup (name, attribute, value) values ('Instrument', 'manufacturer', 'Carl Zeiss');
insert into common_lookup (name, attribute, value) values ('Instrument', 'manufacturer', 'Diagnostica Stago');
insert into common_lookup (name, attribute, value) values ('Instrument', 'manufacturer', 'EDAX');
insert into common_lookup (name, attribute, value) values ('Instrument', 'manufacturer', 'Hitachi');
insert into common_lookup (name, attribute, value) values ('Instrument', 'manufacturer', 'JEOL');
insert into common_lookup (name, attribute, value) values ('Instrument', 'manufacturer', 'Kodak');
insert into common_lookup (name, attribute, value) values ('Instrument', 'manufacturer', 'Malvern');
insert into common_lookup (name, attribute, value) values ('Instrument', 'manufacturer', 'Micromeritics');
insert into common_lookup (name, attribute, value) values ('Instrument', 'manufacturer', 'Molecular Devices');
insert into common_lookup (name, attribute, value) values ('Instrument', 'manufacturer', 'Molecular Imaging');
insert into common_lookup (name, attribute, value) values ('Instrument', 'manufacturer', 'Philips');
insert into common_lookup (name, attribute, value) values ('Instrument', 'manufacturer', 'Quantachrome Instruments');
insert into common_lookup (name, attribute, value) values ('Instrument', 'manufacturer', 'Shimadzu');
insert into common_lookup (name, attribute, value) values ('Instrument', 'manufacturer', 'Tecan');
insert into common_lookup (name, attribute, value) values ('Instrument', 'manufacturer', 'Thermo Electron');
insert into common_lookup (name, attribute, value) values ('Instrument', 'manufacturer', 'Waters');
insert into common_lookup (name, attribute, value) values ('Instrument', 'manufacturer', 'Wyatt Technologies');

insert into common_lookup(name,attribute, value) values ('Condition', 'name','Solvent Media');
insert into common_lookup(name,attribute, value) values ('Condition', 'name','Culture Media');
insert into common_lookup(name,attribute, value) values ('Condition', 'name','Sample Concentration');
insert into common_lookup(name,attribute, value) values ('Condition', 'name','Short Term Storage');
insert into common_lookup(name,attribute, value) values ('Condition', 'name','Long Term Storage');
insert into common_lookup(name,attribute, value) values ('Condition', 'name','Ph');
insert into common_lookup(name,attribute, value) values ('Condition', 'name','Temperature');
insert into common_lookup(name,attribute, value) values ('Condition', 'name','Centrifugation');
insert into common_lookup(name,attribute, value) values ('Condition', 'name','Freeze Thaw');
insert into common_lookup(name,attribute, value) values ('Condition', 'name','Lyophilization');
insert into common_lookup(name,attribute, value) values ('Condition', 'name','Sonication');
insert into common_lookup(name,attribute, value) values ('Condition', 'name','Electromagnetic Radiation');

insert into common_lookup(name,attribute, value) values ('Lyophilization', 'property','time');
insert into common_lookup(name,attribute, value) values ('Solvent Media', 'property','with serum');
insert into common_lookup(name,attribute, value) values ('Solvent Media', 'property','ion concentration');
insert into common_lookup(name,attribute, value) values ('Solvent Media', 'property','ionic strength');
insert into common_lookup(name,attribute, value) values ('Solvent Media', 'property','osmolality');
insert into common_lookup(name,attribute, value) values ('Solvent Media', 'property','molecular formula');
insert into common_lookup(name,attribute, value) values ('Solvent Media', 'property','serum percentage');
insert into common_lookup(name,attribute, value) values ('Culture Media', 'property','media type');
insert into common_lookup(name,attribute, value) values ('Culture Media', 'property','serum percentage');
insert into common_lookup(name,attribute, value) values ('Short Term Storage', 'property','time');
insert into common_lookup(name,attribute, value) values ('Short Term Storage', 'property','lyophilized');
insert into common_lookup(name,attribute, value) values ('Long Term Storage', 'property','time');
insert into common_lookup(name,attribute, value) values ('Long Term Storage', 'property','lyophilized');
insert into common_lookup(name,attribute, value) values ('Lyophilization', 'property','time');
insert into common_lookup(name,attribute, value) values ('Electromagnetic Radiation', 'property','bandwidth');
insert into common_lookup(name,attribute, value) values ('Electromagnetic Radiation', 'property','frequency');
insert into common_lookup(name,attribute, value) values ('Electromagnetic Radiation', 'property','wavelength');
insert into common_lookup(name,attribute, value) values ('Electromagnetic Radiation', 'property','time');
insert into common_lookup(name,attribute, value) values ('Sonication', 'property','number of pulses');
insert into common_lookup(name,attribute, value) values ('Sonication', 'property','pulse duration');

insert into common_lookup(name,attribute,value) values ('NanomaterialEntity','displayName','Nanoparticle Entity');
insert into common_lookup(name,attribute,value) values ('FunctionalizingEntity','displayName','Functionalizing Entity');
insert into common_lookup(name,attribute,value) values ('ChemicalAssociation','displayName','Chemical Association');
insert into common_lookup(name,attribute,value) values ('Relaxivity','displayName','Relaxivity');
insert into common_lookup(name,attribute,value) values ('Sterility','displayName','Sterility');
insert into common_lookup(name,attribute,value) values ('Targeting','displayName','Targeting');
insert into common_lookup(name,attribute,value) values ('MetabolicStability','displayName','Metabolic Stability');

insert into common_lookup(name,attribute,value) values('Sterility', 'assayType', 'Endotoxin');
insert into common_lookup(name,attribute,value) values('Sterility', 'assayType', 'Bacterial/Yeast/Mold');
insert into common_lookup(name,attribute,value) values('Sterility', 'assayType', 'Mycoplasma');
insert into common_lookup(name,attribute,value) values('BloodContact', 'assayType', 'Plasma Protein Binding');
insert into common_lookup(name,attribute,value) values('BloodContact', 'assayType', 'Hemolysis');
insert into common_lookup(name,attribute,value) values('BloodContact', 'assayType', 'Platelet Aggregation');
insert into common_lookup(name,attribute,value) values('BloodContact', 'assayType', 'Coagulation');
insert into common_lookup(name,attribute,value) values('BloodContact', 'assayType', 'Complement Activation');
insert into common_lookup(name,attribute,value) values('ImmuneCellFunction', 'assayType', 'CFU-GM');
insert into common_lookup(name,attribute,value) values('ImmuneCellFunction', 'assayType', 'Leukocyte Proliferation');
insert into common_lookup(name,attribute,value) values('ImmuneCellFunction', 'assayType', 'Phagocytosis');
insert into common_lookup(name,attribute,value) values('ImmuneCellFunction', 'assayType', 'Cytokine Induction');
insert into common_lookup(name,attribute,value) values('ImmuneCellFunction', 'assayType', 'Chemotaxis');
insert into common_lookup(name,attribute,value) values('ImmuneCellFunction', 'assayType', 'Oxidative Burst');
insert into common_lookup(name,attribute,value) values('ImmuneCellFunction', 'assayType', 'Cytotoxic Activity of NK Cells');
insert into common_lookup(name,attribute,value) values('OxidativeStress', 'assayType', 'GSH Homeostasis');
insert into common_lookup(name,attribute,value) values('OxidativeStress', 'assayType', 'Lipid Peroxidation');
insert into common_lookup(name,attribute,value) values('OxidativeStress', 'assayType', 'ROS Generation');
insert into common_lookup(name,attribute,value) values('Targeting', 'assayType', 'Cell Binding/Internalization');
insert into common_lookup(name,attribute,value) values('Targeting', 'assayType', 'Gene Expression');
insert into common_lookup(name,attribute,value) values('Cytotoxicity', 'assayType', 'Cell Viability');
insert into common_lookup(name,attribute,value) values('Cytotoxicity', 'assayType', 'Caspase 3 Apoptosis');
insert into common_lookup(name,attribute,value) values('Cytotoxicity', 'assayType', 'Proliferation');
insert into common_lookup(name,attribute,value) values('Cytotoxicity', 'assayType', 'Mitochondrial Membrane Potential');
insert into common_lookup(name,attribute,value) values('Cytotoxicity', 'assayType', 'Mitochondrial Function');
insert into common_lookup(name,attribute,value) values('Cytotoxicity', 'assayType', 'Gene Expression');
insert into common_lookup(name,attribute,value) values('Sterility', 'assayType', 'Endotoxin');
insert into common_lookup(name,attribute,value) values('Sterility', 'assayType', 'Bacterial/Yeast/Mold');
insert into common_lookup(name,attribute,value) values('Sterility', 'assayType', 'Mycoplasma');

insert into common_lookup(name,attribute,value) values ('Molecular Weight','datumName','molecular weight');
insert into common_lookup(name,attribute,value) values('Purity', 'datumName', '% purity for sample');
insert into common_lookup(name,attribute,value) values('Relaxivity', 'datumName', 'T1');
insert into common_lookup(name,attribute,value) values('Relaxivity', 'datumName', 'T2');
insert into common_lookup(name,attribute,value) values('Relaxivity', 'datumName', 'R1');
insert into common_lookup(name,attribute,value) values('Relaxivity', 'datumName', 'R2');
insert into common_lookup(name,attribute,value) values ('Size','datumName','PDI');
insert into common_lookup(name,attribute,value) values ('Size','datumName','peak1');
insert into common_lookup(name,attribute,value) values ('Size','datumName','RMS-size');
insert into common_lookup(name,attribute,value) values ('Size','datumName','Z-average');
insert into common_lookup(name,attribute,value) values ('Surface','datumName','charge');
insert into common_lookup(name,attribute,value) values ('Surface','datumName','surface area');
insert into common_lookup(name,attribute,value) values ('Surface','datumName','zeta potential');
insert into common_lookup(name,attribute,value) values('Caspase 3 Apoptosis', 'datumName', '% of control');
insert into common_lookup(name,attribute,value) values('Caspase 3 Apoptosis', 'datumName', 'fluorescence');
insert into common_lookup(name,attribute,value) values('Cell Viability', 'datumName', 'LC50');
insert into common_lookup(name,attribute,value) values('Cell Binding/Internalization', 'datumName', 'cellular fluorescence');
insert into common_lookup(name,attribute,value) values ('CFU-GM','datumName','number of CFU-GM colonies');
insert into common_lookup(name,attribute,value) values ('CFU-GM','datumName','total number of bone marrow cells');
insert into common_lookup(name,attribute,value) values ('Chemotaxis', 'datumName',	'% of control');
insert into common_lookup(name,attribute,value) values ('Coagulation', 'datumName',	'Prothrombin Time(PT)');
insert into common_lookup(name,attribute,value) values ('Coagulation', 'datumName',	'Activated Partial Thromboplastin Time (APTT)');
insert into common_lookup(name,attribute,value) values ('Coagulation', 'datumName',	'Thrombin Time');
insert into common_lookup(name,attribute,value) values ('Coagulation', 'datumName',	'Reptilase Time');
insert into common_lookup(name,attribute,value) values ('Complement Activation', 'datumName', 'is complement activation induced');
insert into common_lookup(name,attribute,value) values ('Cytokine Induction', 'datumName','IL10');
insert into common_lookup(name,attribute,value) values ('Cytokine Induction', 'datumName','IL1 Beta');
insert into common_lookup(name,attribute,value) values ('Cytokine Induction', 'datumName','IL8');
insert into common_lookup(name,attribute,value) values ('Cytokine Induction', 'datumName','IL6');
insert into common_lookup(name,attribute,value) values ('Cytokine Induction', 'datumName','TNF Alpha');
insert into common_lookup(name,attribute,value) values ('EnzymeInduction', 'datumName','% of control');
insert into common_lookup(name,attribute,value) values ('Gene Expression', 'datumName', 'cellular fluorescence');
insert into common_lookup(name,attribute,value) values ('Gene Expression', 'datumName', 'fluorescence ratio');
insert into common_lookup(name,attribute,value) values ('GSH Homeostasis', 'datumName', '% of control');
insert into common_lookup(name,attribute,value) values ('Hemolysis','datumName','is hemolytic');
insert into common_lookup(name,attribute,value) values ('Leukocyte Proliferation','datumName','% of control');
insert into common_lookup(name,attribute,value) values ('Lipid Peroxidation', 'datumName', '% of control');
insert into common_lookup(name,attribute,value) values ('Mitochondrial Function', 'datumName', 'luminescence');
insert into common_lookup(name,attribute,value) values ('Mitochondrial Membrane Potential', 'datumName', 'fluorescence ratio');
insert into common_lookup(name,attribute,value) values ('Mitochondrial Membrane Potential', 'datumName', 'ratio of red to green fluorescence');
insert into common_lookup(name,attribute,value) values ('Oxidative Burst', 'datumName', '% of control');
insert into common_lookup(name,attribute,value) values ('Cytotoxic Activity of NK Cells', 'datumName','% of control');
insert into common_lookup(name,attribute,value) values ('Phagocytosis','datumName','Fold Change vs. control');
insert into common_lookup(name,attribute,value) values ('Platelet Aggregation','datumName','is above threshold');
insert into common_lookup(name,attribute,value) values ('Platelet Aggregation','datumName','% of aggregation vs. control');
insert into common_lookup(name,attribute,value) values ('Platelet Aggregation','datumName','% of collagen induced aggregation vs. control');
insert into common_lookup(name,attribute,value) values ('Proliferation', 'datumName', 'ratio of cell line1 to cell line 2');
insert into common_lookup(name,attribute,value) values ('Proliferation', 'datumName', '% of control');
insert into common_lookup(name,attribute,value) values ('Plasma Protein Binding','datumName','protein bound');
insert into common_lookup(name,attribute,value) values ('Plasma Protein Binding','datumName','peptide bound');
insert into common_lookup(name,attribute,value) values ('ROS Generation', 'datumName', '% of control');

insert into common_lookup(name,attribute,value) values ('charge','unit','a.u.');
insert into common_lookup(name,attribute,value) values ('charge','unit','aC');
insert into common_lookup(name,attribute,value) values ('charge','unit','Ah');
insert into common_lookup(name,attribute,value) values ('charge','unit','C');
insert into common_lookup(name,attribute,value) values ('charge','unit','esu');
insert into common_lookup(name,attribute,value) values ('charge','unit','Fr');
insert into common_lookup(name,attribute,value) values ('charge','unit','statC');
insert into common_lookup(name,attribute,value) values ('molecular weight','unit','kDa');
insert into common_lookup(name,attribute,value) values ('peak1','unit','nm');
insert into common_lookup(name,attribute,value) values ('RMS-size','unit','nm');
insert into common_lookup(name,attribute,value) values ('surface area','unit','nm^2');
insert into common_lookup(name,attribute,value) values ('Z-average','unit','nm');
insert into common_lookup(name,attribute,value) values ('zeta potential','unit','mV');
insert into common_lookup(name,attribute, value) values ('Sample Concentration', 'unit','mg/mL');
insert into common_lookup(name,attribute, value) values ('Sample Concentration', 'unit','g/mL');
insert into common_lookup(name,attribute, value) values ('Sample Concentration', 'unit','mg/mL');
insert into common_lookup(name,attribute, value) values ('Sample Concentration', 'unit','ug/uL');
insert into common_lookup(name,attribute, value) values ('Centrifugation', 'unit','g-Force');
insert into common_lookup(name,attribute, value) values ('Centrifugation', 'unit','RPM');
insert into common_lookup(name,attribute, value) values ('ion concentration', 'unit','mol/L');
insert into common_lookup(name,attribute, value) values ('ionic strength', 'unit','mol/L');
insert into common_lookup(name,attribute, value) values ('osmolality', 'unit','osmol/kg');
insert into common_lookup(name,attribute, value) values ('time', 'unit','second');
insert into common_lookup(name,attribute, value) values ('time', 'unit','hour');
insert into common_lookup(name,attribute, value) values ('time', 'unit','Minute');
insert into common_lookup(name,attribute, value) values ('time', 'unit','Day');
insert into common_lookup(name,attribute, value) values ('power', 'unit','Watt');
insert into common_lookup(name,attribute, value) values ('power', 'unit','Kilowatt');
insert into common_lookup(name,attribute, value) values ('temperature', 'unit','Celcius');
insert into common_lookup(name,attribute, value) values ('temperature', 'unit','Fahrenheit');
insert into common_lookup(name,attribute, value) values ('Freeze Thaw', 'unit','Number of Cycles');
insert into common_lookup(name,attribute, value) values ('bandwidth', 'unit','Hz');
insert into common_lookup(name,attribute, value) values ('frequency', 'unit','Hz');
insert into common_lookup(name,attribute, value) values ('wavelength', 'unit','nm');
insert into common_lookup(name,attribute,value) values ('dimension', 'unit', ' nm');
insert into common_lookup(name,attribute,value) values ('luminescence signal', 'unit', 'volt');


ALTER TABLE canano.common_lookup
 CHANGE common_lookup_pk_id common_lookup_pk_id BIGINT(20)  NOT NULL;
