
-- update LabFile table, create columns: title, description, comments
alter table LAB_FILE add (TITLE varchar2(500), 
			  DESCRIPTION varchar2(2000),
			  COMMENTS varchar2(2000));

-- drop SAMPLE_TYPE table
drop table SAMPLE_TYPE;

-- create all new tables
CREATE TABLE SAMPLE_TYPE
(
  SAMPLE_TYPE_PK_ID  NUMBER                     NOT NULL,
  SAMPLE_TYPE_NAME   VARCHAR2(200)
)
LOGGING 
NOCACHE
NOPARALLEL;

CREATE TABLE AGENT
(
  AGENT_PK_ID    NUMBER                         NOT NULL,
  DISCRIMINATOR  VARCHAR2(200),
  DESCRIPTION    VARCHAR2(2000),
  NAME           VARCHAR2(200),
  OTHER          VARCHAR2(200),
  SEQUENCE       VARCHAR2(2000)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE AGENT_TARGET
(
  AGENT_TARGET_PK_ID  NUMBER                    NOT NULL,
  DISCRIMINATOR       VARCHAR2(200),
  NAME                VARCHAR2(200),
  DESCRIPTION         VARCHAR2(2000),
  LIST_INDEX          NUMBER,
  AGENT_PK_ID         NUMBER
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE APPLICATION_ACTION
(
  APPLICATION_ACTION_PK_ID  NUMBER              NOT NULL,
  TYPE_NAME                 VARCHAR2(100),
  ACTION_NAME               VARCHAR2(100)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE ASSOCIATED_FILE
(
  ASSOCIATED_FILE_PK_ID  NUMBER
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE CARBON_NANOTUBE_COMPOSITION
(
  CHIRALITY             VARCHAR2(100),
  GROWTH_DIAMETER       NUMBER,
  AVERAGE_LENGTH        NUMBER,
  WALL_TYPE             VARCHAR2(100),
  CN_COMPOSITION_PK_ID  NUMBER                  NOT NULL
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE CHARACTERIZATION
(
  CHARACTERIZATION_PK_ID  NUMBER                NOT NULL,
  CLASSIFICATION          VARCHAR2(200),
  SOURCE                  VARCHAR2(200),
  DESCRIPTION             VARCHAR2(2000),
  IDENTIFIER_NAME         VARCHAR2(500),
  NAME                    VARCHAR2(100),
  DISCRIMINATOR           VARCHAR2(50),
  CREATED_DATE            DATE,
  CREATED_BY              VARCHAR2(200),
  CHAR_PROTOCOL_PK_ID     NUMBER,
  INSTRUMENT_PK_ID        NUMBER
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE CHARACTERIZATION_PROTOCOL
(
  CHAR_PROTOCOL_PK_ID  NUMBER                   NOT NULL,
  NAME                 VARCHAR2(200),
  VERSION              VARCHAR2(100)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE CHARACTERIZATION_TABLE
(
  CHAR_TABLE_PK_ID        NUMBER                NOT NULL,
  FILE_PATH               VARCHAR2(500),
  TYPE                    VARCHAR2(100),
  CHARACTERIZATION_PK_ID  NUMBER,
  LIST_INDEX              NUMBER,
  LABFILE_PK_ID           NUMBER
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE CHARACTERIZATION_TMP
(
  CHARACTERIZATION_PK_ID  NUMBER                NOT NULL,
  CLASSIFICATION          VARCHAR2(200),
  SOURCE                  VARCHAR2(200),
  DESCRIPTION             VARCHAR2(2000),
  IDENTIFIER_NAME         VARCHAR2(500),
  NAME                    VARCHAR2(100),
  DISCRIMINATOR           VARCHAR2(50),
  CREATED_DATE            DATE,
  CREATED_BY              VARCHAR2(200),
  INSTRUMENT_PK_ID        NUMBER
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE COMPOSING_ELEMENT
(
  COMPOSING_ELEMENT_PK_ID  NUMBER               NOT NULL,
  ELEMENT_TYPE             VARCHAR2(100),
  CHEMICAL_NAME            VARCHAR2(200),
  DESCRIPTION              VARCHAR2(2000),
  CHARACTERIZATION_PK_ID   NUMBER,
  LIST_INDEX               NUMBER
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE CYTOTOXICITY
(
  CYTOTOXICITY_PK_ID  NUMBER                    NOT NULL,
  CELL_LINE           VARCHAR2(200),
  CELL_DEATH_METHOD   VARCHAR2(200)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE DENDRIMER_COMPOSITION
(
  GENERATION           NUMBER,
  MOLECULAR_FORMULA    VARCHAR2(200),
  REPEAT_UNIT          VARCHAR2(100),
  BRANCH               VARCHAR2(200),
  D_COMPOSITION_PK_ID  NUMBER                   NOT NULL
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE DERIVED_DATA_FILE
(
  DERIVED_FILE_PK_ID  NUMBER                    NOT NULL
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE EMULSION_COMPOSITION
(
  EMULSION_TYPE        VARCHAR2(200),
  MOLECULAR_FORMULA    VARCHAR2(200),
  POLYMER_NAME         VARCHAR2(200),
  IS_POLYMERIZED       NUMBER,
  E_COMPOSITION_PK_ID  NUMBER                   NOT NULL
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE FULLERENE_COMPOSITION
(
  NUMBER_OF_CARBON     VARCHAR2(200),
  F_COMPOSITION_PK_ID  NUMBER                   NOT NULL
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE INSTRUMENT
(
  INSTRUMENT_PK_ID       NUMBER                 NOT NULL,
  DESCRIPTION            VARCHAR2(4000),
  INSTRUMENT_TYPE_PK_ID  NUMBER,
  MANUFACTURER_PK_ID     NUMBER
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE INSTRUMENT_TYPE
(
  INSTRUMENT_TYPE_PK_ID  NUMBER                 NOT NULL,
  NAME                   VARCHAR2(200),
  DESCRIPTION            VARCHAR2(4000),
  ABBREVIATION           VARCHAR2(50)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE INSTRUMENT_TYPE_MANUFACTURER
(
  MANUFACTURER_PK_ID     NUMBER                 NOT NULL,
  INSTRUMENT_TYPE_PK_ID  NUMBER                 NOT NULL
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE KEYWORD
(
  KEYWORD_PK_ID  NUMBER                         NOT NULL,
  NAME           VARCHAR2(100)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE KEYWORD_DERIVED_FILE
(
  KEYWORD_PK_ID       NUMBER                    NOT NULL,
  DERIVED_FILE_PK_ID  NUMBER                    NOT NULL
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE KEYWORD_NANOPARTICLE
(
  KEYWORD_PK_ID       NUMBER                    NOT NULL,
  NANOPARTICLE_PK_ID  NUMBER                    NOT NULL
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE LINKAGE
(
  LINKAGE_PK_ID   NUMBER                        NOT NULL,
  DESCRIPTION     VARCHAR2(2000),
  DISCRIMINATOR   VARCHAR2(200),
  BOND_TYPE       VARCHAR2(200),
  LOCALIZATION    VARCHAR2(200),
  FUNCTION_PK_ID  NUMBER,
  LIST_INDEX      NUMBER,
  AGENT_PK_ID     NUMBER
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE LIPOSOME_COMPOSITION
(
  IS_POLYMERIZED       NUMBER,
  POLYMER_NAME         VARCHAR2(200),
  L_COMPOSITION_PK_ID  NUMBER                   NOT NULL
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE MANUFACTURER
(
  MANUFACTURER_PK_ID  NUMBER                    NOT NULL,
  NAME                VARCHAR2(200)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE MORPHOLOGY
(
  MORPHOLOGY_PK_ID  NUMBER                      NOT NULL,
  TYPE              VARCHAR2(100)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE NANOPARTICLE
(
  NANOPARTICLE_PK_ID  NUMBER                    NOT NULL,
  CLASSIFICATION      VARCHAR2(200)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE NANOPARTICLE_CHAR
(
  CHARACTERIZATION_PK_ID  NUMBER                NOT NULL,
  NANOPARTICLE_PK_ID      NUMBER                NOT NULL
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE PARTICLE_FUNCTION
(
  PARTICLE_FUNCTION_PK_ID  NUMBER               NOT NULL,
  TYPE                     VARCHAR2(100),
  ACTIVATION_METHOD        VARCHAR2(500),
  NANOPARTICLE_PK_ID       NUMBER,
  IDENTIFIER_NAME          VARCHAR2(200),
  DESCRIPTION              VARCHAR2(2000)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE POLYMER_COMPOSITION
(
  IS_CROSS_LINK        NUMBER,
  CROSS_LINK_DEGREE    NUMBER,
  INITIATOR            VARCHAR2(200),
  P_COMPOSITION_PK_ID  NUMBER                   NOT NULL
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE REPORT
(
  REPORT_PK_ID  NUMBER                          NOT NULL
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE SAMPLE_ASSOCIATED_FILE
(
  SAMPLE_PK_ID           NUMBER                 NOT NULL,
  ASSOCIATED_FILE_PK_ID  NUMBER                 NOT NULL
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE SAMPLE_REPORT
(
  SAMPLE_PK_ID  NUMBER,
  FILE_PK_ID    NUMBER
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE SHAPE
(
  SHAPE_PK_ID    NUMBER                         NOT NULL,
  MAX_DIMENSION  NUMBER,
  MIN_DIMENSION  NUMBER,
  TYPE           VARCHAR2(100)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE SOLUBILITY
(
  SOLUBILITY_PK_ID        NUMBER                NOT NULL,
  SOLVENT                 VARCHAR2(200),
  CRITICAL_CONCENTRATION  NUMBER,
  CONCENTRATION_UNIT      VARCHAR2(100),
  IS_SOLUBLE              NUMBER
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE STABILITY
(
  STABILITY_PK_ID               NUMBER          NOT NULL,
  LONG_TERM_STORAGE             NUMBER,
  LONG_TERM_STORAGE_UNIT        VARCHAR2(100),
  SHORT_TERM_STORAGE            NUMBER,
  SHORT_TERM_STORAGE_UNIT       VARCHAR2(100),
  STRESS_RESULT                 VARCHAR2(500),
  RELEASE_KINETICS_DESCRIPTION  VARCHAR2(4000),
  MEASUREMENT_TYPE              VARCHAR2(100),
  STRESSOR_TYPE                 VARCHAR2(100),
  STRESSOR_DESC                 VARCHAR2(2000),
  STRESSOR_VALUE                NUMBER,
  STRESSOR_VALUE_UNIT           VARCHAR2(100)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE SURFACE
(
  SURFACE_AREA       NUMBER,
  SURFACE_AREA_UNIT  VARCHAR2(100),
  ZETA_POTENTIAL     NUMBER,
  CHARGE             NUMBER,
  CHARGE_UNIT        VARCHAR2(100),
  IS_HYDROPHOBIC     NUMBER,
  SURFACE_PK_ID      NUMBER                     NOT NULL
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE SURFACE_CHEMISTRY
(
  SURFACE_CHEMISTRY_PK_ID  NUMBER               NOT NULL,
  MOLECULE_NAME            VARCHAR2(200),
  SURFACE_PK_ID            NUMBER,
  NUMBER_MOLECULE          NUMBER,
  LIST_INDEX               NUMBER
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE SURFACE_GROUP
(
  SURFACE_GROUP_PK_ID  NUMBER                   NOT NULL,
  NAME                 VARCHAR2(100),
  MODIFIER             VARCHAR2(100),
  D_COMPOSITION_PK_ID  NUMBER,
  LIST_INDEX           NUMBER
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE TABLE_DATA
(
  TABLE_DATA_PK_ID  NUMBER                      NOT NULL,
  TYPE              VARCHAR2(100),
  VALUE             NUMBER,
  VALUE_UNIT        VARCHAR2(100),
  CHAR_TABLE_PK_ID  NUMBER,
  LIST_INDEX        NUMBER,
  CONTROL_NAME      VARCHAR2(200),
  CONTROL_TYPE      VARCHAR2(100)
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE TABLE TABLE_DATA_CONDITION
(
  TABLE_DATA_COND_PK_ID  NUMBER                 NOT NULL,
  TYPE                   VARCHAR2(100),
  VALUE                  NUMBER,
  VALUE_UNIT             VARCHAR2(100),
  TABLE_DATA_PK_ID       NUMBER,
  LIST_INDEX             NUMBER
)
LOGGING 
NOCACHE
NOPARALLEL;


CREATE UNIQUE INDEX PK_LINKAGE ON LINKAGE
(LINKAGE_PK_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_REPORT ON REPORT
(REPORT_PK_ID)
LOGGING
NOPARALLEL;


ALTER TABLE AGENT ADD (
  PRIMARY KEY (AGENT_PK_ID));


ALTER TABLE AGENT_TARGET ADD (
  PRIMARY KEY (AGENT_TARGET_PK_ID));


ALTER TABLE APPLICATION_ACTION ADD (
  PRIMARY KEY (APPLICATION_ACTION_PK_ID));


ALTER TABLE CARBON_NANOTUBE_COMPOSITION ADD (
  PRIMARY KEY (CN_COMPOSITION_PK_ID));


ALTER TABLE CHARACTERIZATION ADD (
  PRIMARY KEY (CHARACTERIZATION_PK_ID));


ALTER TABLE CHARACTERIZATION_PROTOCOL ADD (
  PRIMARY KEY (CHAR_PROTOCOL_PK_ID));


ALTER TABLE CHARACTERIZATION_TABLE ADD (
  PRIMARY KEY (CHAR_TABLE_PK_ID));


ALTER TABLE COMPOSING_ELEMENT ADD (
  PRIMARY KEY (COMPOSING_ELEMENT_PK_ID));


ALTER TABLE CYTOTOXICITY ADD (
  PRIMARY KEY (CYTOTOXICITY_PK_ID));


ALTER TABLE DENDRIMER_COMPOSITION ADD (
  PRIMARY KEY (D_COMPOSITION_PK_ID));


ALTER TABLE DERIVED_DATA_FILE ADD (
  PRIMARY KEY (DERIVED_FILE_PK_ID));


ALTER TABLE EMULSION_COMPOSITION ADD (
  PRIMARY KEY (E_COMPOSITION_PK_ID));


ALTER TABLE FULLERENE_COMPOSITION ADD (
  PRIMARY KEY (F_COMPOSITION_PK_ID));


ALTER TABLE INSTRUMENT ADD (
  PRIMARY KEY (INSTRUMENT_PK_ID));


ALTER TABLE INSTRUMENT_TYPE ADD (
  PRIMARY KEY (INSTRUMENT_TYPE_PK_ID));


ALTER TABLE INSTRUMENT_TYPE_MANUFACTURER ADD (
  PRIMARY KEY (MANUFACTURER_PK_ID, INSTRUMENT_TYPE_PK_ID));


ALTER TABLE KEYWORD ADD (
  PRIMARY KEY (KEYWORD_PK_ID));


ALTER TABLE KEYWORD_DERIVED_FILE ADD (
  PRIMARY KEY (KEYWORD_PK_ID, DERIVED_FILE_PK_ID));


ALTER TABLE KEYWORD_NANOPARTICLE ADD (
  PRIMARY KEY (KEYWORD_PK_ID, NANOPARTICLE_PK_ID));


ALTER TABLE LINKAGE ADD (
  CONSTRAINT PK_LINKAGE PRIMARY KEY (LINKAGE_PK_ID));


ALTER TABLE LIPOSOME_COMPOSITION ADD (
  PRIMARY KEY (L_COMPOSITION_PK_ID));


ALTER TABLE MANUFACTURER ADD (
  PRIMARY KEY (MANUFACTURER_PK_ID));


ALTER TABLE MORPHOLOGY ADD (
  PRIMARY KEY (MORPHOLOGY_PK_ID));


ALTER TABLE NANOPARTICLE ADD (
  PRIMARY KEY (NANOPARTICLE_PK_ID));


ALTER TABLE NANOPARTICLE_CHAR ADD (
  PRIMARY KEY (CHARACTERIZATION_PK_ID, NANOPARTICLE_PK_ID));


ALTER TABLE PARTICLE_FUNCTION ADD (
  PRIMARY KEY (PARTICLE_FUNCTION_PK_ID));


ALTER TABLE POLYMER_COMPOSITION ADD (
  PRIMARY KEY (P_COMPOSITION_PK_ID));


ALTER TABLE REPORT ADD (
  CONSTRAINT PK_REPORT PRIMARY KEY (REPORT_PK_ID));


ALTER TABLE SHAPE ADD (
  PRIMARY KEY (SHAPE_PK_ID));


ALTER TABLE SOLUBILITY ADD (
  PRIMARY KEY (SOLUBILITY_PK_ID));


ALTER TABLE STABILITY ADD (
  PRIMARY KEY (STABILITY_PK_ID));


ALTER TABLE SURFACE ADD (
  PRIMARY KEY (SURFACE_PK_ID));


ALTER TABLE SURFACE_CHEMISTRY ADD (
  PRIMARY KEY (SURFACE_CHEMISTRY_PK_ID));


ALTER TABLE SURFACE_GROUP ADD (
  PRIMARY KEY (SURFACE_GROUP_PK_ID));


ALTER TABLE TABLE_DATA ADD (
  PRIMARY KEY (TABLE_DATA_PK_ID));


ALTER TABLE TABLE_DATA_CONDITION ADD (
  PRIMARY KEY (TABLE_DATA_COND_PK_ID));


ALTER TABLE TABLE_DATA_CONTROL ADD (
  PRIMARY KEY (TABLE_DATA_CONTROL_PK_ID));


ALTER TABLE AGENT_TARGET ADD (
  CONSTRAINT FK_AGENT_TARGET_AGENT FOREIGN KEY (AGENT_PK_ID) 
    REFERENCES AGENT (AGENT_PK_ID)
    ON DELETE CASCADE);


ALTER TABLE CHARACTERIZATION ADD (
  FOREIGN KEY (INSTRUMENT_PK_ID) 
    REFERENCES INSTRUMENT (INSTRUMENT_PK_ID));

ALTER TABLE CHARACTERIZATION ADD (
  FOREIGN KEY (CHAR_PROTOCOL_PK_ID) 
    REFERENCES CHARACTERIZATION_PROTOCOL (CHAR_PROTOCOL_PK_ID));


ALTER TABLE CHARACTERIZATION_TABLE ADD (
  FOREIGN KEY (CHARACTERIZATION_PK_ID) 
    REFERENCES CHARACTERIZATION (CHARACTERIZATION_PK_ID));


ALTER TABLE INSTRUMENT ADD (
  FOREIGN KEY (INSTRUMENT_TYPE_PK_ID) 
    REFERENCES INSTRUMENT_TYPE (INSTRUMENT_TYPE_PK_ID));

ALTER TABLE INSTRUMENT ADD (
  FOREIGN KEY (MANUFACTURER_PK_ID) 
    REFERENCES MANUFACTURER (MANUFACTURER_PK_ID));


ALTER TABLE INSTRUMENT_TYPE_MANUFACTURER ADD (
  FOREIGN KEY (INSTRUMENT_TYPE_PK_ID) 
    REFERENCES INSTRUMENT_TYPE (INSTRUMENT_TYPE_PK_ID));

ALTER TABLE INSTRUMENT_TYPE_MANUFACTURER ADD (
  FOREIGN KEY (MANUFACTURER_PK_ID) 
    REFERENCES MANUFACTURER (MANUFACTURER_PK_ID));


ALTER TABLE KEYWORD_DERIVED_FILE ADD (
  CONSTRAINT FK_KEYWORD_D_FILE_D_FILE FOREIGN KEY (DERIVED_FILE_PK_ID) 
    REFERENCES DERIVED_DATA_FILE (DERIVED_FILE_PK_ID)
    ON DELETE CASCADE);

ALTER TABLE KEYWORD_DERIVED_FILE ADD (
  CONSTRAINT FK_KEYWORD_D_FILE_KEYWORD FOREIGN KEY (KEYWORD_PK_ID) 
    REFERENCES KEYWORD (KEYWORD_PK_ID)
    ON DELETE CASCADE);


ALTER TABLE KEYWORD_NANOPARTICLE ADD (
  FOREIGN KEY (NANOPARTICLE_PK_ID) 
    REFERENCES NANOPARTICLE (NANOPARTICLE_PK_ID));

ALTER TABLE KEYWORD_NANOPARTICLE ADD (
  FOREIGN KEY (KEYWORD_PK_ID) 
    REFERENCES KEYWORD (KEYWORD_PK_ID));


ALTER TABLE LINKAGE ADD (
  CONSTRAINT FK_LINKAGE_AGENT FOREIGN KEY (AGENT_PK_ID) 
    REFERENCES AGENT (AGENT_PK_ID)
    ON DELETE CASCADE);

ALTER TABLE LINKAGE ADD (
  CONSTRAINT FK_LINKAGE_FUNCTION FOREIGN KEY (FUNCTION_PK_ID) 
    REFERENCES PARTICLE_FUNCTION (PARTICLE_FUNCTION_PK_ID)
    ON DELETE CASCADE);


ALTER TABLE MORPHOLOGY ADD (
  FOREIGN KEY (MORPHOLOGY_PK_ID) 
    REFERENCES CHARACTERIZATION (CHARACTERIZATION_PK_ID)
    ON DELETE CASCADE);


ALTER TABLE NANOPARTICLE ADD (
  FOREIGN KEY (NANOPARTICLE_PK_ID) 
    REFERENCES SAMPLE (SAMPLE_PK_ID));


ALTER TABLE NANOPARTICLE_CHAR ADD (
  FOREIGN KEY (NANOPARTICLE_PK_ID) 
    REFERENCES NANOPARTICLE (NANOPARTICLE_PK_ID));


ALTER TABLE PARTICLE_FUNCTION ADD (
  FOREIGN KEY (NANOPARTICLE_PK_ID) 
    REFERENCES NANOPARTICLE (NANOPARTICLE_PK_ID));


ALTER TABLE SHAPE ADD (
  FOREIGN KEY (SHAPE_PK_ID) 
    REFERENCES CHARACTERIZATION (CHARACTERIZATION_PK_ID)
    ON DELETE CASCADE);


ALTER TABLE SOLUBILITY ADD (
  FOREIGN KEY (SOLUBILITY_PK_ID) 
    REFERENCES CHARACTERIZATION (CHARACTERIZATION_PK_ID)
    ON DELETE CASCADE);


ALTER TABLE STABILITY ADD (
  FOREIGN KEY (STABILITY_PK_ID) 
    REFERENCES CHARACTERIZATION (CHARACTERIZATION_PK_ID)
    ON DELETE CASCADE);


ALTER TABLE SURFACE ADD (
  FOREIGN KEY (SURFACE_PK_ID) 
    REFERENCES CHARACTERIZATION (CHARACTERIZATION_PK_ID)
    ON DELETE CASCADE);


ALTER TABLE SURFACE_CHEMISTRY ADD (
  FOREIGN KEY (SURFACE_PK_ID) 
    REFERENCES SURFACE (SURFACE_PK_ID));


ALTER TABLE SURFACE_GROUP ADD (
  FOREIGN KEY (D_COMPOSITION_PK_ID) 
    REFERENCES DENDRIMER_COMPOSITION (D_COMPOSITION_PK_ID));


ALTER TABLE TABLE_DATA ADD (
  FOREIGN KEY (CHAR_TABLE_PK_ID) 
    REFERENCES CHARACTERIZATION_TABLE (CHAR_TABLE_PK_ID));


ALTER TABLE TABLE_DATA_CONDITION ADD (
  FOREIGN KEY (TABLE_DATA_PK_ID) 
    REFERENCES TABLE_DATA (TABLE_DATA_PK_ID));


ALTER TABLE TABLE_DATA_CONTROL ADD (
  FOREIGN KEY (TABLE_DATA_PK_ID) 
    REFERENCES TABLE_DATA (TABLE_DATA_PK_ID));


