ALTER TABLE NANOPARTICLE_CHAR ADD (
  FOREIGN KEY (CHARACTERIZATION_PK_ID) 
 REFERENCES CHARACTERIZATION (CHARACTERIZATION_PK_ID));
 
ALTER TABLE ASSOCIATED_FILE ADD (
  PRIMARY KEY
 (ASSOCIATED_FILE_PK_ID));
   
ALTER TABLE SAMPLE_ASSOCIATED_FILE ADD (
  FOREIGN KEY (SAMPLE_PK_ID) 
 REFERENCES SAMPLE (SAMPLE_PK_ID));

ALTER TABLE SAMPLE_ASSOCIATED_FILE ADD (
  FOREIGN KEY (ASSOCIATED_FILE_PK_ID) 
 REFERENCES ASSOCIATED_FILE (ASSOCIATED_FILE_PK_ID));

ALTER TABLE SAMPLE_REPORT MODIFY (
  FILE_PK_ID NOT NULL,
  SAMPLE_PK_ID NOT NULL);
  
ALTER TABLE SAMPLE_REPORT ADD (
  FOREIGN KEY (FILE_PK_ID) 
 REFERENCES REPORT (REPORT_PK_ID));

ALTER TABLE SAMPLE_REPORT ADD (
  FOREIGN KEY (SAMPLE_PK_ID) 
 REFERENCES SAMPLE (SAMPLE_PK_ID));
 

ALTER TABLE ASSOCIATED_FILE ADD (
  FOREIGN KEY (ASSOCIATED_FILE_PK_ID) 
 REFERENCES LAB_FILE (FILE_PK_ID));
 
ALTER TABLE REPORT ADD (
  FOREIGN KEY (REPORT_PK_ID) 
 REFERENCES LAB_FILE (FILE_PK_ID));
 
ALTER TABLE KEYWORD_BIOASSAY_DATA ADD (
  FOREIGN KEY (DERIVED_BIOASSAY_DATA_PK_ID) 
 REFERENCES DERIVED_BIOASSAY_DATA (DERIVED_BIOASSAY_DATA_PK_ID));

ALTER TABLE KEYWORD_BIOASSAY_DATA ADD (
  FOREIGN KEY (KEYWORD_PK_ID) 
 REFERENCES KEYWORD (KEYWORD_PK_ID));

ALTER TABLE DERIVED_BIOASSAY_DATA ADD (
  FOREIGN KEY (DERIVED_BIOASSAY_DATA_PK_ID) 
 REFERENCES LAB_FILE (FILE_PK_ID));

ALTER TABLE DERIVED_BIOASSAY_DATA ADD (
  FOREIGN KEY (CHARACTERIZATION_PK_ID) 
 REFERENCES CHARACTERIZATION (CHARACTERIZATION_PK_ID));

ALTER TABLE CHARACTERIZATION ADD (
  FOREIGN KEY (INSTRUMENT_CONFIG_PK_ID) 
 REFERENCES INSTRUMENT_CONFIG (INSTRUMENT_CONFIG_PK_ID));

ALTER TABLE CHARACTERIZATION ADD (
  FOREIGN KEY (PROTOCOL_FILE_PK_ID) 
 REFERENCES PROTOCOL_FILE (PROTOCOL_FILE_PK_ID));

ALTER TABLE DATUM ADD (
  FOREIGN KEY (DERIVED_BIOASSAY_DATA_PK_ID) 
 REFERENCES DERIVED_BIOASSAY_DATA (DERIVED_BIOASSAY_DATA_PK_ID));
 
ALTER TABLE DATUM_CONDITION ADD (
  FOREIGN KEY (DATUM_PK_ID) 
 REFERENCES DATUM (DATUM_PK_ID));

ALTER TABLE PROTOCOL_FILE ADD (
  FOREIGN KEY (PROTOCOL_FILE_PK_ID) 
 REFERENCES LAB_FILE (FILE_PK_ID));
 
ALTER TABLE CYTOTOXICITY ADD (
  FOREIGN KEY (CYTOTOXICITY_PK_ID) 
 REFERENCES CHARACTERIZATION (CHARACTERIZATION_PK_ID));

ALTER TABLE POLYMER_COMPOSITION ADD (
  FOREIGN KEY (P_COMPOSITION_PK_ID) 
 REFERENCES CHARACTERIZATION (CHARACTERIZATION_PK_ID));

ALTER TABLE CARBON_NANOTUBE_COMPOSITION ADD (
  FOREIGN KEY (CN_COMPOSITION_PK_ID) 
 REFERENCES CHARACTERIZATION (CHARACTERIZATION_PK_ID));

ALTER TABLE DENDRIMER_COMPOSITION ADD (
  FOREIGN KEY (D_COMPOSITION_PK_ID) 
 REFERENCES CHARACTERIZATION (CHARACTERIZATION_PK_ID));

ALTER TABLE EMULSION_COMPOSITION ADD (
  FOREIGN KEY (E_COMPOSITION_PK_ID) 
 REFERENCES CHARACTERIZATION (CHARACTERIZATION_PK_ID));

ALTER TABLE FULLERENE_COMPOSITION ADD (
  FOREIGN KEY (F_COMPOSITION_PK_ID) 
 REFERENCES CHARACTERIZATION (CHARACTERIZATION_PK_ID));
 
ALTER TABLE LIPOSOME_COMPOSITION ADD (
  FOREIGN KEY (L_COMPOSITION_PK_ID) 
 REFERENCES CHARACTERIZATION (CHARACTERIZATION_PK_ID));

ALTER TABLE COMPOSING_ELEMENT ADD (
  FOREIGN KEY (CHARACTERIZATION_PK_ID) 
 REFERENCES CHARACTERIZATION (CHARACTERIZATION_PK_ID));



