function FileData_Pairs(x)
{
x.t("managing","cananolab");
x.t("navigation.","section");
x.t("topics:","cananolab");
x.t("interface","navigation.");
x.t("working","files");
x.t("working","cananolab");
x.t("inventory","working");
x.t("getting","started");
x.t("includes","following");
x.t("cananolab","interface");
x.t("cananolab","inventory");
x.t("cananolab","1.0");
x.t("cananolab","workflow");
x.t("cananolab","online");
x.t("cananolab","using");
x.t("introduces","cananolab");
x.t("started","cananolab");
x.t("1.0","getting");
x.t("1.0","section");
x.t("workflow","managing");
x.t("section","includes");
x.t("section","introduces");
x.t("online","help");
x.t("help","working");
x.t("following","topics:");
x.t("using","cananolab");
}
