function FileData_Pairs(x)
{
x.t("protocols","cananolab");
x.t("protocols","nanoparticle");
x.t("managing","protocols");
x.t("managing","characterizations");
x.t("discussed","section");
x.t("sample","nanoparticle");
x.t("publish","reports");
x.t("annotating","nanoparticles");
x.t("cananolab","allows");
x.t("cananolab","topics");
x.t("allows","submit");
x.t("functions","nanoparticle");
x.t("nanoparticles","publish");
x.t("nanoparticles","annotating");
x.t("nanoparticles","submit");
x.t("feature","cananolab");
x.t("annotations","nanoparticles");
x.t("section","include");
x.t("submitting","nanoparticle");
x.t("reports","submit");
x.t("include","sample");
x.t("characterizations","managing");
x.t("characterizations","submitting");
x.t("submit","protocols");
x.t("submit","feature");
x.t("submit","annotations");
x.t("topics","discussed");
x.t("nanoparticle","functions");
x.t("nanoparticle","report");
x.t("nanoparticle","characterizations");
x.t("nanoparticle","definitions");
x.t("definitions","managing");
}
