function FileData_Pairs(x)
{
x.t("searching","aliquots");
x.t("searching","nanoparticles");
x.t("searching","calab");
x.t("searching","workflow");
x.t("searching","samples");
x.t("describes","calab");
x.t("launching","calab");
x.t("aliquots","searching");
x.t("features","associate");
x.t("include:","launching");
x.t("\u00adcussed","section");
x.t("search","searching");
x.t("searches.","topics");
x.t("calab","features");
x.t("calab","search");
x.t("calab","database");
x.t("workflow","searching");
x.t("dis","\u00adcussed");
x.t("section","describes");
x.t("section","include:");
x.t("samples","searching");
x.t("database","searching");
x.t("database","searches.");
x.t("database","section");
x.t("topics","dis");
x.t("associate","database");
}
