function FileData_Pairs(x)
{
x.t("subcategory","immunotoxcity");
x.t("subcategory","vitro");
x.t("tree","vitro");
x.t("blood","contact");
x.t("contact","immune");
x.t("immune","cell");
x.t("characterization","immunotoxicity");
x.t("characterization","toxicity");
x.t("cell","function");
x.t("subcategories","blood");
x.t("function","subcategories");
x.t("immunotoxicity","toxicity");
x.t("immunotoxicity","two");
x.t("immunotoxcity","immunotoxicity");
x.t("immunotoxcity","toxicity");
x.t("immunotoxcity","navigation");
x.t("toxicity","subcategory");
x.t("characterizations","adding");
x.t("two","subcategories");
x.t("navigation","tree");
x.t("vitro","characterization");
x.t("vitro","characterizations");
x.t("adding","vitro");
}
