function FileData_Pairs(x)
{
x.t("composition","category");
x.t("tree.","section");
x.t("managing","characterizations");
x.t("files","category");
x.t("tree","function");
x.t("tree","section");
x.t("tree","navigation");
x.t("describes","manage");
x.t("topics:","understanding");
x.t("physical","characterization");
x.t("includes","following");
x.t("characterization","category");
x.t("nanoparticles","information");
x.t("function","category");
x.t("section","describes");
x.t("section","includes");
x.t("reports","category");
x.t("information","navigation");
x.t("characterizations","associated");
x.t("navigation","tree.");
x.t("navigation","tree");
x.t("vitro","characterization");
x.t("manage","nanoparticles");
x.t("following","topics:");
x.t("understanding","navigation");
x.t("associated","files");
x.t("category","composition");
x.t("category","managing");
x.t("category","physical");
x.t("category","reports");
x.t("category","vitro");
}
