function FileData_Pairs(x)
{
x.t("subcategory","enzyme");
x.t("subcategory","vitro");
x.t("tree","vitro");
x.t("summary","multiple");
x.t("summary","view");
x.t("multiple","characterizations");
x.t("induction","oxicity");
x.t("induction","enzyme");
x.t("induction","toxicity");
x.t("induction","navigation");
x.t("induction","vitro");
x.t("oxicity","subcategory");
x.t("add","enzyme");
x.t("characterization","add");
x.t("characterization","display");
x.t("characterization","displaying");
x.t("characterization","following");
x.t("characterization","category");
x.t("display","summary");
x.t("display","detail");
x.t("enzyme","induction");
x.t("view","characterization");
x.t("view","enzyme");
x.t("toxicity","subcategory");
x.t("characterizations","display");
x.t("characterizations","displaying");
x.t("displaying","summary");
x.t("displaying","detail");
x.t("navigation","tree");
x.t("vitro","characterization");
x.t("vitro","characterizations");
x.t("following","adding");
x.t("adding","enzyme");
x.t("category","toxicity");
x.t("detail","view");
}
