<tr>
	<td>
		<h4>
			Manage Publications
		</h4>
	</td>
	<td align="right" width="20%">
		<jsp:include page="/webHelp/helpGlossary.jsp">
			<jsp:param name="topic" value="manage_reports_help" />
			<jsp:param name="glossaryTopic" value="glossary_help" />
		</jsp:include>		
	</td>
</tr>
<tr>
	<td colspan="2" class="welcomeContent">
		This is the manage publications section which allows users to submit publications and
		reports associated with a nanoparticle sample.  Publications can include review papers, 
		journals, book chapters, and other forms of published documents.  A report is a document
		generated by a research organization that may describe the composition of a nanoparticle
		and the results of physical, in vitro, and in vivo nanoparticle characterizations.  In
		this section, depending on your authorization level, you may submit a new publication or
		search for an existing publication.
		<br>
</tr>
