<tr>
	<td>
		<h4>
			Manage Report Home
		</h4>
	</td>
	<td align="right" width="15%">
		<a
			href="javascript:openHelpWindow('webHelp/index.html?single=true&amp;context=caNanoLab&amp;topic=manage_reports_help')"
			class="helpText">Help</a>
	</td>
</tr>
<tr>
	<td colspan="2" class="welcomeContent">
		This is the manage report section. A report is a document generated by
		a given research organization to describe the physical characteristics
		and the
		<em>in vitro</em> and
		<em>in vivo </em>properties of the nanoparticles.&nbsp; Please begin
		by selecting either Create a New Report or Select Existing Reports.
		<br>
		<br>
</tr>
