function FileData_Pairs(x)
{
x.t("searching","sample");
x.t("searching","workflow");
x.t("launching","calab");
x.t("working","calab");
x.t("sample","containers");
x.t("sample","ali");
x.t("0.5","allows");
x.t("initiate","search");
x.t("menu","option.");
x.t("\u00adquot","detail");
x.t("search","launching");
x.t("search","sample");
x.t("search","menu");
x.t("search","search");
x.t("search","calab");
x.t("search","workflow");
x.t("allows","search");
x.t("option.","information");
x.t("calab","launching");
x.t("calab","0.5");
x.t("calab","search");
x.t("calab","online");
x.t("workflow","searching");
x.t("workflow","information");
x.t("information.","initiate");
x.t("and/or","search");
x.t("online","help");
x.t("help","working");
x.t("information","searching");
x.t("information","and/or");
x.t("ali","\u00adquot");
x.t("detail","information.");
}
