package gov.nih.nci.cagrid.cananolab.common;

import javax.xml.namespace.QName;


/**
 * This class is autogenerated, DO NOT EDIT
 *
 * @created by Introduce Toolkit version 1.3
 */
public interface CaNanoLabServiceConstantsBase {
	public static final String SERVICE_NS = "http://cananolab.cagrid.nci.nih.gov/CaNanoLabService";
	public static final QName RESOURCE_KEY = new QName(SERVICE_NS, "CaNanoLabServiceKey");
	public static final QName RESOURCE_PROPERTY_SET = new QName(SERVICE_NS, "CaNanoLabServiceResourceProperties");
	public static final QName DOMAINMODEL = new QName("gme://caGrid.caBIG/1.0/gov.nih.nci.cagrid.metadata.dataservice", "DomainModel");
	public static final QName SERVICEMETADATA = new QName("gme://caGrid.caBIG/1.0/gov.nih.nci.cagrid.metadata", "ServiceMetadata");
	
}
