function FileData_Pairs(x)
{
x.t("managing","samples");
x.t("right","browser");
x.t("deleting","sample");
x.t("action","deletes");
x.t("sample","managing");
x.t("sample","deleting");
x.t("sample","open");
x.t("sample","delete");
x.t("sample","cananolab");
x.t("sample","page");
x.t("sample","update");
x.t("open","sample");
x.t("deletes","sample");
x.t("delete","sample");
x.t("delete","button");
x.t("editing","sample");
x.t("browser","window");
x.t("cananolab","database");
x.t("updating","sample");
x.t("window","confirm");
x.t("confirm","deletion");
x.t("scenes","scheduled");
x.t("button","lower");
x.t("samples","editing");
x.t("executed","behind");
x.t("lower","right");
x.t("database","executed");
x.t("click","delete");
x.t("deletion","action");
x.t("page","click");
x.t("page","described");
x.t("behind","scenes");
x.t("described","updating");
x.t("scheduled","time");
x.t("update","sample");
}
