function FileData_Pairs(x)
{
x.t("curating","data");
x.t("managing","collaboration");
x.t("describes","create");
x.t("describes","link");
x.t("(csm)","create");
x.t("create","users");
x.t("create","manage");
x.t("(upt)","describes");
x.t("user","provisioning");
x.t("link","nci\u2019s");
x.t("security","module");
x.t("common","security");
x.t("nci\u2019s","common");
x.t("tasks","cananolab");
x.t("cananolab","managing");
x.t("collaboration","groups");
x.t("processes","topics");
x.t("section","describes");
x.t("section","include");
x.t("groups","curating");
x.t("groups","curation");
x.t("include","following");
x.t("curation","processes");
x.t("administrative","tasks");
x.t("module","(csm)");
x.t("tool","(upt)");
x.t("provisioning","tool");
x.t("administration","section");
x.t("administration","administration");
x.t("users","user");
x.t("topics","section");
x.t("manage","collaboration");
x.t("following","administrative");
}
