function FileData_Pairs(x)
{
x.t("subcategory","blood");
x.t("blood","contact");
x.t("contact","blood");
x.t("contact","subcategories");
x.t("contact","toxicity");
x.t("contact","navigation");
x.t("tree","vitro");
x.t("characterization","adding");
x.t("characterization","category");
x.t("coagulation","vitro");
x.t("aggregation","vitro");
x.t("subcategories","include");
x.t("protein","binding");
x.t("immunotoxicity","subcategory");
x.t("include","following");
x.t("platelet","aggregation");
x.t("toxicity","immunotoxicity");
x.t("hemolysis","vitro");
x.t("plasma","protein");
x.t("navigation","tree");
x.t("vitro","characterization");
x.t("following","adding");
x.t("adding","coagulation");
x.t("adding","platelet");
x.t("adding","hemolysis");
x.t("adding","plasma");
x.t("category","toxicity");
x.t("binding","vitro");
}
