function FileData_Pairs(x)
{
x.t("home","page");
x.t("interface","navigation");
x.t("public","information");
x.t("getting","started");
x.t("includes","following");
x.t("cananolab","home");
x.t("cananolab","interface");
x.t("cananolab","welcome");
x.t("cananolab","1.4");
x.t("cananolab","login");
x.t("cananolab","online");
x.t("introduces","cananolab");
x.t("welcome","cananolab");
x.t("started","cananolab");
x.t("1.4","getting");
x.t("1.4","section");
x.t("section","includes");
x.t("section","introduces");
x.t("login","page");
x.t("online","help");
x.t("help","cananolab");
x.t("page","browsing");
x.t("information","welcome");
x.t("browsing","public");
x.t("topics","using");
x.t("navigation","section");
x.t("following","topics");
x.t("using","cananolab");
}
