function FileData_Pairs(x)
{
x.t("managing","calab");
x.t("create","samples");
x.t("execute","workflow");
x.t("working","calab");
x.t("aliquots.","tasks");
x.t("getting","started");
x.t("overview","execute");
x.t("relates","workflow");
x.t("functionality","overview");
x.t("functionality","relates");
x.t("tasks","described");
x.t("started","calab");
x.t("review","calab");
x.t("1.0","working");
x.t("calab","create");
x.t("calab","inventory");
x.t("calab","functionality");
x.t("calab","1.0");
x.t("calab","workflow");
x.t("workflow","working");
x.t("workflow","getting");
x.t("workflow","review");
x.t("workflow","calab");
x.t("samples","aliquots.");
x.t("described","managing");
}
