function FileData_Pairs(x)
{
x.t("managing","documents");
x.t("submissions","edited");
x.t("editing","documents");
x.t("document","submissions");
x.t("clicking","edit");
x.t("edit","[document}");
x.t("publication","page");
x.t("documents","managing");
x.t("documents","editing");
x.t("documents","document");
x.t("button","report");
x.t("edited","clicking");
x.t("report","page");
x.t("[document}","button");
x.t("page","publication");
x.t("page","update");
x.t("update","publication");
x.t("update","report");
}
