function FileData_Pairs(x)
{
x.t("managing","characterizations");
x.t("tree","managing");
x.t("tree","perform");
x.t("deleting","characterization");
x.t("physical","invitro");
x.t("copying","characterizations");
x.t("characterization","tasks");
x.t("tasks","characterization");
x.t("tasks","navigation");
x.t("tasks","manage");
x.t("perform","following");
x.t("cananolab","copying");
x.t("invitro","characterizations");
x.t("characterizations","deleting");
x.t("characterizations","characterization");
x.t("characterizations","cananolab");
x.t("navigation","tree");
x.t("following","tasks");
x.t("manage","physical");
}
