function FileData_Pairs(x)
{
x.t("managing","characterizations");
x.t("tree","managing");
x.t("tree","section");
x.t("describes","manage");
x.t("includes","following");
x.t("characterization","tasks");
x.t("tasks","publication");
x.t("publication","category");
x.t("viewing","characterizations");
x.t("section","describes");
x.t("section","includes");
x.t("characterizations","characterization");
x.t("characterizations","section");
x.t("characterizations","navigation");
x.t("topics","viewing");
x.t("navigation","tree");
x.t("manage","nanoparticle");
x.t("following","topics");
x.t("nanoparticle","characterizations");
}
