function FileData_Pairs(x)
{
x.t("subcategory","oxidative");
x.t("subcategory","vitro");
x.t("tree","vitro");
x.t("summary","multiple");
x.t("multiple","characterizations");
x.t("induction","vitro");
x.t("add","enzyme");
x.t("characterization","add");
x.t("characterization","display");
x.t("characterization","viewing");
x.t("characterization","toxicity");
x.t("characterization","following");
x.t("display","summary");
x.t("display","detail");
x.t("enzyme","induction");
x.t("viewing","characterizations");
x.t("view","characterization");
x.t("toxicity","subcategory");
x.t("characterizations","display");
x.t("characterizations","adding");
x.t("oxidative","stress");
x.t("navigation","tree");
x.t("vitro","characterization");
x.t("vitro","characterizations");
x.t("following","adding");
x.t("adding","enzyme");
x.t("adding","vitro");
x.t("stress","toxicity");
x.t("stress","oxidative");
x.t("stress","navigation");
x.t("detail","view");
}
