function FileData_Pairs(x)
{
x.t("cananolab.","copying");
x.t("managing","characterizations");
x.t("tree","managing");
x.t("tree","perform");
x.t("deleting","characterization");
x.t("physical","characterization");
x.t("physical","invitro");
x.t("copying","characterizations");
x.t("characterization","files");
x.t("characterization","loading");
x.t("tasks","manage");
x.t("perform","following");
x.t("loading","physical");
x.t("invitro","characterizations");
x.t("characterizations","cananolab.");
x.t("characterizations","managing");
x.t("characterizations","deleting");
x.t("characterizations","navigation");
x.t("navigation","tree");
x.t("following","tasks");
x.t("manage","physical");
}
