function FileData_Pairs(x)
{
x.t("searching","nanoparticles");
x.t("searching","calab");
x.t("page.","page");
x.t("launching","calab");
x.t("particle.","information");
x.t("displays","annotate");
x.t("displays","general");
x.t("details","searching");
x.t("details","nanoparticle");
x.t("results","page.");
x.t("annotate","particle.");
x.t("search","searching");
x.t("search","results");
x.t("nanoparticles","nanoparticle");
x.t("calab","search");
x.t("calab","database");
x.t("opens","click");
x.t("hypertext","links");
x.t("database","launching");
x.t("click","hypertext");
x.t("page","displays");
x.t("page","opens");
x.t("information","page");
x.t("information","nanoparticle");
x.t("column","nanoparticle");
x.t("links","nanoparticle");
x.t("general","information");
x.t("nanoparticle","details");
x.t("nanoparticle","search");
x.t("nanoparticle","column");
x.t("nanoparticle","general");
}
