function FileData_Pairs(x)
{
x.t("managing","cananolab");
x.t("create","samples");
x.t("execute","workflow");
x.t("working","cananolab");
x.t("aliquots.","tasks");
x.t("getting","started");
x.t("overview","execute");
x.t("relates","workflow");
x.t("functionality","overview");
x.t("functionality","relates");
x.t("tasks","described");
x.t("cananolab","create");
x.t("cananolab","inventory");
x.t("cananolab","functionality");
x.t("cananolab","1.0");
x.t("cananolab","workflow");
x.t("started","cananolab");
x.t("review","cananolab");
x.t("1.0","working");
x.t("workflow","working");
x.t("workflow","getting");
x.t("workflow","cananolab");
x.t("workflow","review");
x.t("samples","aliquots.");
x.t("described","managing");
}
