function FileData_Pairs(x)
{
x.t("searching","nanoparticle");
x.t("managing","reports");
x.t("describes","cananolab");
x.t("discussed","section");
x.t("cananolab\u2019s","report");
x.t("features","topics");
x.t("features","associate");
x.t("overview","submitting/updating");
x.t("cananolab","features");
x.t("report","searching");
x.t("report","features");
x.t("section","describes");
x.t("section","include");
x.t("submitting/updating","report");
x.t("reports","managing");
x.t("reports","overview");
x.t("reports","section");
x.t("include","reports");
x.t("topics","discussed");
x.t("associate","cananolab\u2019s");
x.t("nanoparticle","reports");
}
