function FileData_Pairs(x)
{
x.t("tree","section");
x.t("tree","vitro");
x.t("describes","ascribe");
x.t("ascribe","vitro");
x.t("includes","following");
x.t("characterization","overview");
x.t("overview","toxicity");
x.t("nanoparticles","navigation");
x.t("section","describes");
x.t("section","includes");
x.t("toxicity","category");
x.t("characterizations","nanoparticles");
x.t("characterizations","section");
x.t("characterizations","navigation");
x.t("topics","understanding");
x.t("navigation","tree");
x.t("vitro","characterization");
x.t("vitro","characterizations");
x.t("following","topics");
x.t("understanding","navigation");
}
