function FileData_Pairs(x)
{
x.t("composition","section");
x.t("composition","navigation");
x.t("tree","sample");
x.t("tree","section");
x.t("describes","manage");
x.t("sample","composition");
x.t("includes","following");
x.t("nanoparticles","information");
x.t("section","describes");
x.t("section","includes");
x.t("information","navigation");
x.t("topics","understanding");
x.t("navigation","tree");
x.t("manage","nanoparticles");
x.t("following","topics");
x.t("understanding","navigation");
}
