function FileData_Pairs(x)
{
x.t("managing","nanoparticles");
x.t("description","anoparticle");
x.t("description","nanoparticle");
x.t("various","targeting");
x.t("anoparticle","nanoparticle");
x.t("drug","carriers");
x.t("serve","drug");
x.t("particles","used");
x.t("carriers","imaging");
x.t("size","measured");
x.t("drugs","imaging");
x.t("agents","various");
x.t("agents","antibodies");
x.t("agents","reporters");
x.t("antibodies","drugs");
x.t("overview","description");
x.t("nanometers","particles");
x.t("biomedical","applications");
x.t("small","stable");
x.t("targeting","agents");
x.t("reporters","attached");
x.t("nanoparticles","overview");
x.t("nanoparticles","nanoparticles");
x.t("whose","size");
x.t("imaging","agents");
x.t("measured","nanometers");
x.t("surface","nanoparticle");
x.t("attached","surface");
x.t("defined","small");
x.t("stable","particle");
x.t("applications","serve");
x.t("particle","whose");
x.t("used","biomedical");
x.t("nanoparticle","managing");
x.t("nanoparticle","description");
x.t("nanoparticle","defined");
}
