function FileData_Pairs(x)
{
x.t("searching","nanoparticle");
x.t("managing","documents");
x.t("describes","cananolab");
x.t("discussed","section");
x.t("editing","documents");
x.t("cananolab\u2019s","document");
x.t("document","features");
x.t("features","topics");
x.t("features","associate");
x.t("overview","submitting");
x.t("publication","submitting");
x.t("cananolab","features");
x.t("documents","managing");
x.t("documents","editing");
x.t("documents","overview");
x.t("documents","section");
x.t("report","searching");
x.t("section","describes");
x.t("section","include");
x.t("submitting","publication");
x.t("submitting","report");
x.t("include","documents");
x.t("topics","discussed");
x.t("associate","cananolab\u2019s");
x.t("nanoparticle","documents");
}
