function FileData_Pairs(x)
{
x.t("tree","vitro");
x.t("subcategory","vitro");
x.t("cytotoxicity","comprises");
x.t("cytotoxicity","toxicity");
x.t("subcategory:","cytoxicity");
x.t("viability","vitro");
x.t("characterization","cytotoxicity");
x.t("characterization","adding");
x.t("characterization","category");
x.t("subcategories:","adding");
x.t("cell","viability");
x.t("caspase","activity");
x.t("activity","vitro");
x.t("comprises","two");
x.t("toxicity","subcategory");
x.t("toxicity","subcategory:");
x.t("two","subcategories:");
x.t("navigation","tree");
x.t("vitro","characterization");
x.t("cytoxicity","cytotoxicity");
x.t("cytoxicity","toxicity");
x.t("cytoxicity","navigation");
x.t("adding","cell");
x.t("adding","caspase");
x.t("category","toxicity");
}
