function FileData_Pairs(x)
{
x.t("tree","vitro");
x.t("subcategory","vitro");
x.t("blood","contact");
x.t("contact","immune");
x.t("immune","cell");
x.t("subcategory:","immunotoxcity");
x.t("characterization","immunotoxicity");
x.t("characterization","category");
x.t("cell","function");
x.t("subcategories","blood");
x.t("function","subcategories.");
x.t("immunotoxicity","two");
x.t("immunotoxcity","immunotoxcity");
x.t("immunotoxcity","toxicity");
x.t("immunotoxcity","navigation");
x.t("toxicity","subcategory");
x.t("toxicity","subcategory:");
x.t("two","subcategories");
x.t("navigation","tree");
x.t("vitro","characterization");
x.t("category","toxicity");
}
